name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  another_flushbar: ^1.10.28
  animated_splash_screen: ^1.1.0
  intl: ^0.17.0
  form_field_validator: ^1.1.0
  sqflite: ^2.0.2
  path_provider: ^2.0.9
  curved_navigation_bar: ^1.0.3
  carousel_slider: ^4.0.0
  image_picker: ^0.8.4+10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2


flutter_icons:
  image_path: "images/logo.png"
  android: true
  ios: true
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
   - images/
  fonts:
    - family: NoyhR_regular
      fonts:
        - asset: fonts/NoyhR_Regular.ttf
    - family: NoyhR_Bold
      fonts:
        - asset: fonts/NoyhR_Bold.ttf
    - family: Cambria_Regular
      fonts:
        - asset: fonts/Cambria_Regular.ttf
    - family: Cambria_Bold
      fonts:
        - asset: fonts/Cambria_Bold.ttf
    - family: Georgia_Regular
      fonts:
        - asset: fonts/Georgia_Regular.ttf
    - family: Georgia_Bold
      fonts:
        - asset: fonts/Georgia_Bold.ttf
