class Foods{
  final index;
  final cal;
  final image;
  final name;
  const Foods({
    required this.index,
    required this.cal,
    required this.image,
    required this.name,
  });
}

const  foodList = const [
  Foods(index: 1, cal: 100, image: "images/aloo-gobi.jpg", name: "Aloo Gobi"),
  Foods(index: 2, cal: 100, image: "images/aloo-palak.jpg", name: "Aloo Palak"),
  Foods(index: 3, cal: 100, image: "images/Chai.jpg", name: "Chai"),
  Foods(index: 4, cal: 100, image: "images/Channa-Dal.jpg", name: "Channa Dal"),
  Foods(index: 5, cal: 100, image: "images/Chapli-Kabab.jpg", name: "Chapli Kabab"),
  Foods(index: 6, cal: 100, image: "images/Chicken-Baryani.jpg", name: "Chicken Baryani"),
  Foods(index: 7, cal: 100, image: "images/Chicken-Chargha.jpg", name: "Chicken Chargha"),
  Foods(index: 8, cal: 100, image: "images/Chicken-Kofta.jpg", name: "Chicken Kofta"),
  Foods(index: 9, cal: 100, image: "images/Chicken-Korma.jpg", name: "Chicken Korama"),
  Foods(index: 10, cal: 100, image: "images/Chicken-Malai-Tikka.jpg", name: "Malai Tikka"),
  Foods(index: 11, cal: 100, image: "images/Chicken-Parmesan-Slider-Bake.jpg", name: "Chicken Slider"),
  Foods(index: 12, cal: 100, image: "images/Chicken-Tikka-Leg-Recipe.jpg", name: "Chicken Tikka"),
  Foods(index: 13, cal: 100, image: "images/Chocolate-Biscuit-Pudding.jpg", name: "Pudding"),
  Foods(index: 14, cal: 100, image: "images/chocolate_chip_cookies1.jpg", name: "Cookies"),
  Foods(index: 15, cal: 100, image: "images/Egg-Sandwich.jpg", name: "Egg Sandwich"),
  Foods(index: 16, cal: 100, image: "images/eggs.jpg", name: "Eggs"),
  Foods(index: 17, cal: 100, image: "images/Fried-Prosciutto-Tortellini.jpg", name: "Tortellini"),
  Foods(index: 18, cal: 100, image: "images/gajar-halwa.jpg", name: "Gajar Halwa"),
  Foods(index: 19, cal: 100, image: "images/Grilled-Tomato-Peach-Pizza.jpg", name: "Peach Pizza"),
  Foods(index: 20, cal: 100, image: "images/Balochi-tikka.jpg", name: "Balochi Tikka"),
  Foods(index: 21, cal: 100, image: "images/Ham-n-Cheese-Biscuit-Stacks.jpg", name: "Ham-n-Cheese"),
  Foods(index: 22, cal: 100, image: "images/Hot-Artichoke-Spinach-Dip.jpg", name: "Artichoke"),
  Foods(index: 23, cal: 100, image: "images/keema-naan.jpg", name: "Keema Naan"),
  Foods(index: 24, cal: 100, image: "images/lab-e-shireen.jpg", name: "Lab-e-Shireen"),
  Foods(index: 25, cal: 100, image: "images/mango-kulfi.jpg", name: "Mango Kulfi"),
  Foods(index: 26, cal: 100, image: "images/Masoor-Daal.jpg", name: "Masoor Daal"),
  Foods(index: 27, cal: 100, image: "images/nan-khatai.jpg", name: "Nan Khatai"),
  Foods(index: 28, cal: 100, image: "images/Orange-Glazed-Meatballs.jpg", name: "Glazed Meatballs"),
  Foods(index: 29, cal: 100, image: "images/Pakistani-chowmein-noodle.jpg", name: "Chowmein"),
  Foods(index: 30, cal: 100, image: "images/pancakes.jpg", name: "Pancakes"),
  Foods(index: 31, cal: 100, image: "images/parata.jpg", name: "Parata"),
  Foods(index: 32, cal: 100, image: "images/Rice-Kheer.jpg", name: "Rice Kherr"),
  Foods(index: 33, cal: 100, image: "images/Sarsoon-ka-saag.jpg", name: "Sarsoon Saag"),
  Foods(index: 34, cal: 100, image: "images/seekh-kaba.jpg", name: "Seekh Kabab"),
  Foods(index: 35, cal: 100, image: "images/shahi-tukda.jpg", name: "Shahi Tukda"),
  Foods(index: 36, cal: 100, image: "images/sooji-halwa.jpg", name: "Sooji Halwa"),
  Foods(index: 37, cal: 100, image: "images/Teriyaki-Meatballs.jpg", name: "Teriyaki Meatballs"),
  Foods(index: 38, cal: 100, image: "images/Tuscan-Sausage-Bean-Dip.jpg", name: "Tuscan Bean"),
  Foods(index: 39, cal: 100, image: "images/Yakhni-Pulao.jpg", name: "Yakhni Pulao"),
  Foods(index: 40, cal: 100, image: "images/air-fryer-breaded-pork-chop-1.jpg", name: "Pork Chop"),
  Foods(index: 41, cal: 100, image: "images/apple-crumble.jpg", name: "Apple Crumble"),
  Foods(index: 42, cal: 100, image: "images/avocado-crisps.jpg", name: "Avocado Crisps"),
  Foods(index: 43, cal: 100, image: "images/banana-nutella-crepe.jpg", name: "Banana Nutella"),
  Foods(index: 44, cal: 100, image: "images/beef-skewers.jpg", name: "Beef Skewers"),
  Foods(index: 45, cal: 100, image: "images/beef-stew.jpg", name: "Beef Stew"),
  Foods(index: 46, cal: 100, image: "images/blood-orange-beet-smoothie.jpg", name: "Beet Smoothie"),
  Foods(index: 47, cal: 100, image: "images/chocolate-pudding-olive-oil-sea-salt.jpg", name: "Chocolate Pudding"),
  Foods(index: 48, cal: 100, image: "images/coconut-shrimp-2.jpg", name: "Coconut Shrimp"),
  Foods(index: 49, cal: 100, image: "images/cream-cheese-cucumbers-waterbury.jpg", name: "Cheese Cucumbers"),
  Foods(index: 50, cal: 100, image: "images/Crock-pot-beef-ragu-recipe.jpg", name: "Crock Pot Beef"),
  Foods(index: 51, cal: 100, image: "images/crock-pot-chicke-noodle-soup-recipe.jpg", name: "Chicken Noodle"),
  Foods(index: 52, cal: 100, image: "images/fudgy-pumpkin-brownie-bites.jpg", name: "Fudge Pumpkin"),
  Foods(index: 53, cal: 100, image: "images/gluten-free-chicken-fingers-chipotle-honey.jpg", name: "Chicken fingers"),
  Foods(index: 54, cal: 100, image: "images/gluten-free-crispy-rosemary-potatoes.jpg", name: "Rosemary Potatoes"),
  Foods(index: 55, cal: 100, image: "images/grilled-cheese-sauteed-mushrooms.jpg", name: "Cheese Mushrooms"),
  Foods(index: 56, cal: 100, image: "images/grilled-chicken-salad-cranberries-avacado-goat-cheese.jpg", name: "Chicken Salad"),
  Foods(index: 57, cal: 100, image: "images/healthy-barbecue-chicken-pizza.jpg", name: "Barbecue Pizza"),
  Foods(index: 58, cal: 100, image: "images/healthy-black-bean-omelet.jpg", name: "Black Bean Omelet"),
  Foods(index: 59, cal: 100, image: "images/healthy-blueberry-pancakes.jpg", name: "Blueberry Pancakes"),
  Foods(index: 60, cal: 100, image: "images/healthy-blueberry-peach-cobbler.jpg", name: "Blueberry Cobbler"),
  Foods(index: 61, cal: 100, image: "images/healthy-butternut-squash-soup.jpg", name: "Butternut Squash"),
  Foods(index: 62, cal: 100, image: "images/healthy-caprese-sandwich.jpg", name: "Carprese Sandwich"),
  Foods(index: 63, cal: 100, image: "images/healthy-chicken-burger-sundried-tomato-aioli.jpg", name: "Burger with Sundried Tomato"),
  Foods(index: 64, cal: 100, image: "images/healthy-chicken-fried-rice.jpg", name: "Chicken Fried Rice"),
  Foods(index: 65, cal: 100, image: "images/healthy-chicken-under-a-brick.jpg", name: "Chicken Brick"),
  Foods(index: 66, cal: 100, image: "images/healthy-chipotle-shrimp-quesadilla.jpg", name: "Shrimp Quesadilla"),
  Foods(index: 67, cal: 100, image: "images/healthy-egg-sandwich-with-pastrami-and-swiss-recipe.jpg", name: "Sandwich with Pastrami"),
  Foods(index: 68, cal: 100, image: "images/healthy-fiery-buffalo-wings.jpg", name: "Fiery Buffalo Wings"),
  Foods(index: 69, cal: 100, image: "images/healthy-grilled-calamari-salad.jpg", name: "Grilled Calamari"),
  Foods(index: 70, cal: 100, image: "images/healthy-grilled-mahi-mahi-salsa-verde.jpg", name: "Mahi Salsa Verde"),
  Foods(index: 71, cal: 100, image: "images/healthy-grilled-veggie-wrap.jpg", name: "Grilled Veggie Wrap"),
  Foods(index: 72, cal: 100, image: "images/healthy-guacamole.jpg", name: "Guacamole"),
  Foods(index: 73, cal: 100, image: "images/healthy-italian-tuna-melt.jpg", name: "Italian Tuna Melt"),
  Foods(index: 74, cal: 100, image: "images/healthy-loaded-alfredo-chicken-vegetables.jpg", name: "Chicken Vegetable"),
  Foods(index: 75, cal: 100, image: "images/healthy-meatballs-polenta.jpg", name: "Meatballs Polenta"),
  Foods(index: 76, cal: 100, image: "images/healthy-oatmeal–chocolate-chip-cookies.jpg", name: "Oatmeal Chocolate"),
  Foods(index: 77, cal: 100, image: "images/healthy-oatmeal-pancakes-cinnamon-apples.jpg", name: "Oatmeal Pancake"),
  Foods(index: 78, cal: 100, image: "images/healthy-oatmeal-with-eapnut-butter-and-banana-recipe.jpg", name: "Oatmeal and Banana"),
  Foods(index: 79, cal: 100, image: "images/healthy-pork-tenderloin-grilled-pineapple-salsa.jpg", name: "Tenderloin Pork"),
  Foods(index: 80, cal: 100, image: "images/healthy-red-pepper-alfredo.jpg", name: "Red Pepper Alfredo"),
  Foods(index: 81, cal: 100, image: "images/healthy-smokey-deviled-eggs.jpg", name: "Smokey Eggs"),
  Foods(index: 82, cal: 100, image: "images/healthy-spaghetti-spicy-tomato-sauce.jpg", name: "Spaghetti Tomato Sauce"),
  Foods(index: 83, cal: 100, image: "images/healthy-turkey-b-l-t-salad.jpg", name: "Turkey Salad"),
  Foods(index: 84, cal: 100, image: "images/healthy-ultimate-club-sandwich-with-super-mayo.jpg", name: "Club Sandwich"),
  Foods(index: 85, cal: 100, image: "images/healthy-waffles-ham-egg.jpg", name: "Waffles Ham Egg"),
  Foods(index: 86, cal: 100, image: "images/how-to-make-restaurant-salsa-4.jpg", name: "Salsa"),
  Foods(index: 87, cal: 100, image: "images/instant-pot-cheesy-cauliflower-3.jpg", name: "Instant Pot Cauliflower"),
  Foods(index: 88, cal: 100, image: "images/instant-pot-lemon-chicken-2.jpg", name: "Instant Pot Chicken"),
  Foods(index: 89, cal: 100, image: "images/instant-pot-shimp-and-broccoli-4-1.jpg", name: "Shrimp and Broccoli"),
  Foods(index: 90, cal: 100, image: "images/Instant-Pot-steak-fajitas-2.jpg", name: "Steak Fajitas"),
  Foods(index: 91, cal: 100, image: "images/italian-panini-provolone-peppers-arugula.jpg", name: "Italian Burger"),
  Foods(index: 92, cal: 100, image: "images/keto-bacon-cheese-sandwich.jpg", name: "Cheese Sandwich"),
  Foods(index: 93, cal: 100, image: "images/keto-berries-and-cream-overnight-oats.jpg", name: "Berries and Cream"),
  Foods(index: 94, cal: 100, image: "images/keto-cheeseburger-casserole-2.jpg", name: "Cheeseburger Casserole"),
  Foods(index: 95, cal: 100, image: "images/keto-pizza-cups-overhead.jpg", name: "Pizza Cups"),
  Foods(index: 96, cal: 100, image: "images/keto-roast-chicken.jpg", name: "Roast Chicken"),
  Foods(index: 97, cal: 100, image: "images/keto-shredded-pork-shoulder.jpg", name: "Shredded Pork"),
  Foods(index: 98, cal: 100, image: "images/keto-zucchini-noodles.jpg", name: "Zucchini Noodles"),
  Foods(index: 99, cal: 100, image: "images/lentil-veggie-tots-hot-dish-1.jpg", name: "Lentil Veggie Tots"),
  Foods(index: 100, cal: 100, image: "images/low-calorie-apple-pie-crunch-topping.jpg", name: "Apple Pie"),
  Foods(index: 101, cal: 100, image: "images/low-calorie-bolognese-fettuccine-turkey.jpg", name: "Fettuccine Turkey"),
  Foods(index: 102, cal: 100, image: "images/low-calorie-cheesesteak-sandwich.jpg", name: "CheeseStack Sandwich"),
  Foods(index: 103, cal: 100, image: "images/low-calorie-chicken-mole-enchiladas.jpg", name: "Chicken Role"),
  Foods(index: 104, cal: 100, image: "images/low-calorie-fudgy-brownies.jpg", name: "Fudge Brownies"),
  Foods(index: 105, cal: 100, image: "images/low-calorie-grilled-caesar-salad.jpg", name: "Caesar Salad"),
  Foods(index: 106, cal: 100, image: "images/low-calorie-huevos-rancheros.jpg", name: "Huevos Rancheros"),
  Foods(index: 107, cal: 100, image: "images/low-calorie-ricotta-cheesecake-warm-blueberries.jpg", name: "Ricotta CheeseCake"),
  Foods(index: 108, cal: 100, image: "images/low-calorie-spinach-ham-quiche.jpg", name: "Spinach Ham"),
  Foods(index: 109, cal: 100, image: "images/low-calorie-thai-beef-lettuce-wraps.jpg", name: "Thai Beef Lettuce"),
  Foods(index: 110, cal: 100, image: "images/low-carb-vanilla-bourbon-french-toast.jpg", name: "Vanilla Bourbon"),
  Foods(index: 111, cal: 100, image: "images/mediterranean-tofu-veggiescramble.jpg", name: "Tofu Veggie Scramble"),
  Foods(index: 112, cal: 100, image: "images/molten-chocolate-cake.jpg", name: "Molten Chocolate"),
  Foods(index: 113, cal: 100, image: "images/pistachio-cheese-ball-3.jpg", name: "Pistachio Ball"),
  Foods(index: 114, cal: 100, image: "images/plant-based-cali-veggie-burger-with-egg.jpg", name: "Veggie Burger"),
  Foods(index: 115, cal: 100, image: "images/protein-powder-pancakes.jpg", name: "Powder Pancake"),
  Foods(index: 116, cal: 100, image: "images/pumpkin-mole-chili.jpg", name: "Pumpkin Chili"),
  Foods(index: 117, cal: 100, image: "images/raspberry-smoothie.jpg", name: "Raspberry Smoothie"),
  Foods(index: 118, cal: 100, image: "images/seared-ginger-cumin-swordfish-blueberry-avocado-salsa.png", name: "SwordFish with Blueberry"),
  Foods(index: 119, cal: 100, image: "images/shakshuka-paleo-casserole.jpg", name: "Paleo Casserole"),
  Foods(index: 120, cal: 100, image: "images/sheet-pan-pork-chops.jpg", name: "Pan Pork Chops"),
  Foods(index: 121, cal: 100, image: "images/strawberry-rhubarb-ice-recipe.jpg", name: "Strawberry Rhubarb"),
  Foods(index: 122, cal: 100, image: "images/taco-pasta.jpg", name: "Taco Pasta"),
  Foods(index: 123, cal: 100, image: "images/vegan-sausage-sheet-pan.jpg", name: "Vegan Sausage"),
  Foods(index: 124, cal: 100, image: "images/paleo-asian-chicken-meatballs.jpg", name: "Asian Chicken Meatballs"),
  Foods(index: 125, cal: 100, image: "images/paleo-chicken-pot-stickers.jpg", name: "Chicken Pot Skickers"),
  Foods(index: 126, cal: 100, image: "images/paleo-grilled-chicken-pinapple-sandwich.jpg", name: "Grilled Chicken Sandwich"),
  Foods(index: 127, cal: 100, image: "images/paleo-linguine-clams.jpg", name: "Linguine Clams"),
  Foods(index: 128, cal: 100, image: "images/paleo-meatball-soup.jpg", name: "Meatballs Soup"),
  Foods(index: 129, cal: 100, image: "images/paleo-oven-fried-chicken.jpg", name: "Oven Fried Chicken"),
  Foods(index: 130, cal: 100, image: "images/paleo-plum-muffins.jpg", name: "Plum Muffins"),
  Foods(index: 131, cal: 100, image: "images/paleo-scallops-with-chimichurri.jpg", name: "Scallops With Chimichurri"),
  Foods(index: 132, cal: 100, image: "images/paleo-seared-tuna-tacos.jpg", name: "Seared Tuna Tacos"),
  Foods(index: 133, cal: 100, image: "images/paleo-steak-eggs-chimichurri.jpg", name: "Steak with Eggs"),
  Foods(index: 134, cal: 100, image: "images/paleo-swedish-meatballs.jpg", name: "Swedish Meatballs"),
  Foods(index: 135, cal: 100, image: "images/paleo-sweet-spicy-beef.jpg", name: "Spicy Beef"),
  Foods(index: 136, cal: 100, image: "images/vegetarian-artichoke-dip-1.jpg", name: "Veggie Artichoke Dip"),
  Foods(index: 137, cal: 100, image: "images/vegetarian-bruschetta-two-ways.jpg", name: "Veggie Bruschetta"),
  Foods(index: 138, cal: 100, image: "images/vegetarian-butternut-ravioli-sage-brown-butter.jpg", name: "Butternut Ravioli"),
  Foods(index: 139, cal: 100, image: "images/vegetarian-caprese-tomato-towers.jpg", name: "Carpese Tomato Tower"),
  Foods(index: 140, cal: 100, image: "images/vegetarian-green-bean-casserole.jpg", name: "Green Bean Casserole"),
  Foods(index: 141, cal: 100, image: "images/vegetarian-grilled-mexican-style-corn.jpg", name: "Grilled Mexican Corn"),
  Foods(index: 141, cal: 100, image: "images/vegetarian-melted-brie-vegetables.jpg", name: "Melted brie Vegetables"),
  Foods(index: 143, cal: 100, image: "images/vegetarian-warm-goat-cheese-salad.jpg", name: "Goat Cheese Salad"),
  Foods(index: 144, cal: 100, image: "images/Whole30-Green-Machine-Casserole.jpg", name: "Machine Casserole"),
  Foods(index: 145, cal: 100, image: "images/Whole30-Lemon-Cake.jpg", name: "Lemon Cake"),
  // Foods(index: 146, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 147, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 148, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 149, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 150, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 151, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 152, cal: 100, image: "images/.jpg", name: ""),


];