class Foods{
  final index;
  final cal;
  final image;
  final name;
  const Foods({
    required this.index,
    required this.cal,
    required this.image,
    required this.name,
  });
}

const  foodList = const [
  Foods(index: 1, cal: 100, image: "images/Lunch/aloo-gobi.jpg", name: "Aloo Gobi"),
  Foods(index: 2, cal: 100, image: "images/Lunch/aloo-palak.jpg", name: "Aloo Palak"),
  Foods(index: 3, cal: 100, image: "images/Lunch/Pakistani-chowmein-noodle.jpg", name: "Chowmein"),
  Foods(index: 4, cal: 100, image: "images/Lunch/Channa-Dal.jpg", name: "Channa Dal"),
  Foods(index: 5, cal: 100, image: "images/Lunch/Chapli-Kabab.jpg", name: "Chapli Kabab"),
  Foods(index: 6, cal: 100, image: "images/Lunch/Chicken-Baryani.jpg", name: "Chicken Baryani"),
  Foods(index: 7, cal: 100, image: "images/Lunch/Chicken-Chargha.jpg", name: "Chicken Chargha"),
  Foods(index: 8, cal: 100, image: "images/Lunch/Chicken-Kofta.jpg", name: "Chicken Kofta"),
  Foods(index: 9, cal: 100, image: "images/Lunch/Chicken-Korma.jpg", name: "Chicken Korama"),
  Foods(index: 10, cal: 100, image: "images/Lunch/Chicken-Malai-Tikka.jpg", name: "Malai Tikka"),
  Foods(index: 11, cal: 100, image: "images/Lunch/Chicken-Parmesan-Slider-Bake.jpg", name: "Chicken Slider"),
  Foods(index: 12, cal: 100, image: "images/Lunch/Chicken-Tikka-Leg-Recipe.jpg", name: "Chicken Tikka"),
  Foods(index: 13, cal: 100, image: "images/Dessert/Chocolate-Biscuit-Pudding.jpg", name: "Pudding"),
  Foods(index: 14, cal: 100, image: "images/Dessert/CHOCOLATE-CHIP-COOKIES.jpg", name: "Cookies"),
  Foods(index: 15, cal: 100, image: "images/BreakFast/Egg-Sandwich.jpg", name: "Egg Sandwich"),
  Foods(index: 16, cal: 100, image: "images/BreakFast/eggs.jpg", name: "Eggs"),
  Foods(index: 17, cal: 100, image: "images/appetizer/Fried-Prosciutto-Tortellini.jpg", name: "Tortellini"),
  Foods(index: 18, cal: 100, image: "images/Dessert/gajar-halwa.jpg", name: "Gajar Halwa"),
  Foods(index: 19, cal: 100, image: "images/Lunch/Grilled-Tomato-Peach-Pizza.jpg", name: "Peach Pizza"),
  Foods(index: 20, cal: 100, image: "images/Lunch/Balochi-tikka.jpg", name: "Balochi Tikka"),
  Foods(index: 21, cal: 100, image: "images/appetizer/Ham-n-Cheese-Biscuit-Stacks.jpg", name: "Ham-n-Cheese"),
  Foods(index: 22, cal: 100, image: "images/Lunch/Hot-Artichoke-Spinach-Dip.jpg", name: "Artichoke"),
  Foods(index: 23, cal: 100, image: "images/Lunch/keema-naan.jpg", name: "Keema Naan"),
  Foods(index: 24, cal: 100, image: "images/Dessert/lab-e-shireen.jpg", name: "Lab-e-Shireen"),
  Foods(index: 25, cal: 100, image: "images/Dessert/mango-kulfi.jpg", name: "Mango Kulfi"),
  Foods(index: 26, cal: 100, image: "images/Lunch/Masoor-Daal.jpg", name: "Masoor Daal"),
  Foods(index: 27, cal: 100, image: "images/appetizer/nan-khatai.jpg", name: "Nan Khatai"),
  Foods(index: 28, cal: 100, image: "images/Lunch/Orange-Glazed-Meatballs.jpg", name: "Glazed Meatballs"),
  Foods(index: 29, cal: 100, image: "images/BreakFast/Chai.jpg", name: "Chai"),
  Foods(index: 30, cal: 100, image: "images/Dessert/pancakes.jpg", name: "Pancakes"),
  Foods(index: 31, cal: 100, image: "images/BreakFast/parata.jpg", name: "Parata"),
  Foods(index: 32, cal: 100, image: "images/Dessert/Rice-Kheer.jpg", name: "Rice Kherr"),
  Foods(index: 33, cal: 100, image: "images/Lunch/Sarsoon-ka-saag.jpg", name: "Sarsoon Saag"),
  Foods(index: 34, cal: 100, image: "images/Lunch/seekh-kaba.jpg", name: "Seekh Kabab"),
  Foods(index: 35, cal: 100, image: "images/Lunch/shahi-tukda.jpg", name: "Shahi Tukda"),
  Foods(index: 36, cal: 100, image: "images/Dessert/sooji-halwa.jpg", name: "Sooji Halwa"),
  Foods(index: 37, cal: 100, image: "images/Lunch/Teriyaki-Meatballs.jpg", name: "Teriyaki Meatballs"),
  Foods(index: 38, cal: 100, image: "images/Lunch/Tuscan-Sausage-Bean-Dip.jpg", name: "Tuscan Bean"),
  Foods(index: 39, cal: 100, image: "images/Lunch/Yakhni-Pulao.jpg", name: "Yakhni Pulao"),
  Foods(index: 40, cal: 100, image: "images/Lunch/air-fryer-breaded-pork-chop-1.jpg", name: "Pork Chop"),
  // Foods(index: 41, cal: 100, image: "images/apple-crumble.jpg", name: "Apple Crumble"),
  Foods(index: 42, cal: 100, image: "images/Lunch/avocado-crisps.jpg", name: "Avocado Crisps"),
  Foods(index: 43, cal: 100, image: "images/appetizer/banana-nutella-crepe.jpg", name: "Banana Nutella"),
  Foods(index: 44, cal: 100, image: "images/Lunch/beef-skewers.jpg", name: "Beef Skewers"),
  Foods(index: 45, cal: 100, image: "images/Lunch/beef-stew.jpg", name: "Beef Stew"),
  Foods(index: 46, cal: 100, image: "images/Dessert/blood-orange-beet-smoothie.jpg", name: "Beet Smoothie"),
  Foods(index: 47, cal: 100, image: "images/Dessert/chocolate-pudding-olive-oil-sea-salt.jpg", name: "Chocolate Pudding"),
  Foods(index: 48, cal: 100, image: "images/appetizer/coconut-shrimp-2.jpg", name: "Coconut Shrimp"),
  Foods(index: 49, cal: 100, image: "images/appetizer/cream-cheese-cucumbers-waterbury.jpg", name: "Cheese Cucumbers"),
  Foods(index: 50, cal: 100, image: "images/Lunch/Crock-pot-beef-ragu-recipe.jpg", name: "Crock Pot Beef"),
  Foods(index: 51, cal: 100, image: "images/Lunch/crock-pot-chicke-noodle-soup-recipe.jpg", name: "Chicken Noodle"),
  Foods(index: 52, cal: 100, image: "images/Dessert/fudgy-pumpkin-brownie-bites.jpg", name: "Fudge Pumpkin"),
  Foods(index: 53, cal: 100, image: "images/Lunch/gluten-free-chicken-fingers-chipotle-honey.jpg", name: "Chicken fingers"),
  Foods(index: 54, cal: 100, image: "images/Lunch/gluten-free-crispy-rosemary-potatoes.jpg", name: "Rosemary Potatoes"),
  Foods(index: 55, cal: 100, image: "images/Lunch/grilled-cheese-sauteed-mushrooms.jpg", name: "Cheese Mushrooms"),
  Foods(index: 56, cal: 100, image: "images/Lunch/grilled-chicken-salad-cranberries-avacado-goat-cheese.jpg", name: "Chicken Salad"),
  Foods(index: 57, cal: 100, image: "images/Lunch/healthy-barbecue-chicken-pizza.jpg", name: "Barbecue Pizza"),
  Foods(index: 58, cal: 100, image: "images/Lunch/healthy-black-bean-omelet.jpg", name: "Black Bean Omelet"),
  Foods(index: 59, cal: 100, image: "images/BreakFast/healthy-blueberry-pancakes.jpg", name: "Blueberry Pancakes"),
  Foods(index: 60, cal: 100, image: "images/Lunch/healthy-blueberry-peach-cobbler.jpg", name: "Blueberry Cobbler"),
  Foods(index: 61, cal: 100, image: "images/Lunch/healthy-butternut-squash-soup.jpg", name: "Butternut Squash"),
  Foods(index: 62, cal: 100, image: "images/Lunch/healthy-caprese-sandwich.jpg", name: "Carprese Sandwich"),
  Foods(index: 63, cal: 100, image: "images/Lunch/healthy-chicken-burger-sundried-tomato-aioli.jpg", name: "Burger with Sundried Tomato"),
  Foods(index: 64, cal: 100, image: "images/Lunch/healthy-chicken-fried-rice.jpg", name: "Chicken Fried Rice"),
  Foods(index: 65, cal: 100, image: "images/Lunch/healthy-chicken-under-a-brick.jpg", name: "Chicken Brick"),
  Foods(index: 66, cal: 100, image: "images/Lunch/healthy-chipotle-shrimp-quesadilla.jpg", name: "Shrimp Quesadilla"),
  Foods(index: 67, cal: 100, image: "images/Lunch/healthy-egg-sandwich-with-pastrami-and-swiss-recipe.jpg", name: "Sandwich with Pastrami"),
  Foods(index: 68, cal: 100, image: "images/Lunch/healthy-fiery-buffalo-wings.jpg", name: "Fiery Buffalo Wings"),
  Foods(index: 69, cal: 100, image: "images/Lunch/healthy-grilled-calamari-salad.jpg", name: "Grilled Calamari"),
  Foods(index: 70, cal: 100, image: "images/Lunch/healthy-grilled-mahi-mahi-salsa-verde.jpg", name: "Mahi Salsa Verde"),
  Foods(index: 71, cal: 100, image: "images/Lunch/healthy-grilled-veggie-wrap.jpg", name: "Grilled Veggie Wrap"),
  // Foods(index: 72, cal: 100, image: "images/healthy-guacamole.jpg", name: "Guacamole"),
  Foods(index: 73, cal: 100, image: "images/Lunch/healthy-italian-tuna-melt.jpg", name: "Italian Tuna Melt"),
  Foods(index: 74, cal: 100, image: "images/Lunch/healthy-loaded-alfredo-chicken-vegetables.jpg", name: "Chicken Vegetable"),
  Foods(index: 75, cal: 100, image: "images/Lunch/healthy-meatballs-polenta.jpg", name: "Meatballs Polenta"),
  Foods(index: 76, cal: 100, image: "images/Dessert/healthy-oatmeal–chocolate-chip-cookies.jpg", name: "Oatmeal Chocolate"),
  Foods(index: 77, cal: 100, image: "images/appetizer/healthy-oatmeal-pancakes-cinnamon-apples.jpg", name: "Oatmeal Pancake"),
  Foods(index: 78, cal: 100, image: "images/appetizer/healthy-oatmeal-with-eapnut-butter-and-banana-recipe.jpg", name: "Oatmeal and Banana"),
  Foods(index: 79, cal: 100, image: "images/Lunch/healthy-pork-tenderloin-grilled-pineapple-salsa.jpg", name: "Tenderloin Pork"),
  Foods(index: 80, cal: 100, image: "images/Lunch/healthy-red-pepper-alfredo.jpg", name: "Red Pepper Alfredo"),
  Foods(index: 81, cal: 100, image: "images/Lunch/healthy-smokey-deviled-eggs.jpg", name: "Smokey Eggs"),
  Foods(index: 82, cal: 100, image: "images/Lunch/healthy-spaghetti-spicy-tomato-sauce.jpg", name: "Spaghetti Tomato Sauce"),
  Foods(index: 83, cal: 100, image: "images/appetizer/healthy-turkey-b-l-t-salad.jpg", name: "Turkey Salad"),
  Foods(index: 84, cal: 100, image: "images/Lunch/healthy-ultimate-club-sandwich-with-super-mayo.jpg", name: "Club Sandwich"),
  Foods(index: 85, cal: 100, image: "images/Lunch/healthy-waffles-ham-egg.jpg", name: "Waffles Ham Egg"),
  Foods(index: 86, cal: 100, image: "images/appetizer/how-to-make-restaurant-salsa-4.jpg", name: "Salsa"),
  Foods(index: 87, cal: 100, image: "images/appetizer/instant-pot-cheesy-cauliflower-3.jpg", name: "Instant Pot Cauliflower"),
  Foods(index: 88, cal: 100, image: "images/Lunch/instant-pot-lemon-chicken-2.jpg", name: "Instant Pot Chicken"),
  Foods(index: 89, cal: 100, image: "images/Lunch/instant-pot-shimp-and-broccoli-4-1.jpg", name: "Shrimp and Broccoli"),
  Foods(index: 90, cal: 100, image: "images/Lunch/Instant-Pot-steak-fajitas-2.jpg", name: "Steak Fajitas"),
  Foods(index: 91, cal: 100, image: "images/Lunch/italian-panini-provolone-peppers-arugula.jpg", name: "Italian Burger"),
  Foods(index: 92, cal: 100, image: "images/Lunch/keto-bacon-cheese-sandwich.jpg", name: "Cheese Sandwich"),
  Foods(index: 93, cal: 100, image: "images/appetizer/keto-berries-and-cream-overnight-oats.jpg", name: "Berries and Cream"),
  // Foods(index: 94, cal: 100, image: "images/keto-cheeseburger-casserole-2.jpg", name: "Cheeseburger Casserole"),
  Foods(index: 95, cal: 100, image: "images/Lunch/keto-pizza-cups-overhead.jpg", name: "Pizza Cups"),
  Foods(index: 96, cal: 100, image: "images/Lunch/keto-roast-chicken.jpg", name: "Roast Chicken"),
  Foods(index: 97, cal: 100, image: "images/Lunch/keto-shredded-pork-shoulder.jpg", name: "Shredded Pork"),
  Foods(index: 98, cal: 100, image: "images/Lunch/keto-zucchini-noodles.jpg", name: "Zucchini Noodles"),
  Foods(index: 99, cal: 100, image: "images/Lunch/lentil-veggie-tots-hot-dish-1.jpg", name: "Lentil Veggie Tots"),
  Foods(index: 100, cal: 100, image: "images/Dessert/low-calorie-apple-pie-crunch-topping.jpg", name: "Apple Pie"),
  Foods(index: 101, cal: 100, image: "images/Lunch/low-calorie-bolognese-fettuccine-turkey.jpg", name: "Fettuccine Turkey"),
  Foods(index: 102, cal: 100, image: "images/Lunch/low-calorie-cheesesteak-sandwich.jpg", name: "CheeseStack Sandwich"),
  Foods(index: 103, cal: 100, image: "images/Lunch/low-calorie-chicken-mole-enchiladas.jpg", name: "Chicken Role"),
  Foods(index: 104, cal: 100, image: "images/Dessert/low-calorie-fudgy-brownies.jpg", name: "Fudge Brownies"),
  Foods(index: 105, cal: 100, image: "images/Lunch/low-calorie-grilled-caesar-salad.jpg", name: "Caesar Salad"),
  Foods(index: 106, cal: 100, image: "images/Lunch/low-calorie-huevos-rancheros.jpg", name: "Huevos Rancheros"),
  Foods(index: 107, cal: 100, image: "images/Lunch/low-calorie-ricotta-cheesecake-warm-blueberries.jpg", name: "Ricotta CheeseCake"),
  Foods(index: 108, cal: 100, image: "images/Lunch/low-calorie-spinach-ham-quiche.jpg", name: "Spinach Ham"),
  // Foods(index: 109, cal: 100, image: "images/low-calorie-thai-beef-lettuce-wraps.jpg", name: "Thai Beef Lettuce"),
  // Foods(index: 110, cal: 100, image: "images/low-carb-vanilla-bourbon-french-toast.jpg", name: "Vanilla Bourbon"),
  Foods(index: 111, cal: 100, image: "images/Lunch/mediterranean-tofu-veggiescramble.jpg", name: "Tofu Veggie Scramble"),
  Foods(index: 112, cal: 100, image: "images/Dessert/molten-chocolate-cake.jpg", name: "Molten Chocolate"),
  Foods(index: 113, cal: 100, image: "images/Lunch/pistachio-cheese-ball-3.jpg", name: "Pistachio Ball"),
  Foods(index: 114, cal: 100, image: "images/Lunch/plant-based-cali-veggie-burger-with-egg.jpg", name: "Veggie Burger"),
  Foods(index: 115, cal: 100, image: "images/Dessert/protein-powder-pancakes.jpg", name: "Powder Pancake"),
  Foods(index: 116, cal: 100, image: "images/Lunch/pumpkin-mole-chili.jpg", name: "Pumpkin Chili"),
  Foods(index: 117, cal: 100, image: "images/Dessert/raspberry-smoothie.jpg", name: "Raspberry Smoothie"),
  Foods(index: 118, cal: 100, image: "images/Lunch/seared-ginger-cumin-swordfish-blueberry-avocado-salsa.png", name: "SwordFish with Blueberry"),
  Foods(index: 119, cal: 100, image: "images/Lunch/shakshuka-paleo-casserole.jpg", name: "Paleo Casserole"),
  Foods(index: 120, cal: 100, image: "images/Lunch/sheet-pan-pork-chops.jpg", name: "Pan Pork Chops"),
  // Foods(index: 121, cal: 100, image: "images/strawberry-rhubarb-ice-recipe.jpg", name: "Strawberry Rhubarb"),
  Foods(index: 122, cal: 100, image: "images/Lunch/taco-pasta.jpg", name: "Taco Pasta"),
  Foods(index: 123, cal: 100, image: "images/Lunch/vegan-sausage-sheet-pan.jpg", name: "Vegan Sausage"),
  Foods(index: 124, cal: 100, image: "images/Lunch/paleo-asian-chicken-meatballs.jpg", name: "Asian Chicken Meatballs"),
  Foods(index: 125, cal: 100, image: "images/Lunch/paleo-chicken-pot-stickers.jpg", name: "Chicken Pot Skickers"),
  Foods(index: 126, cal: 100, image: "images/Lunch/paleo-grilled-chicken-pinapple-sandwich.jpg", name: "Grilled Chicken Sandwich"),
  Foods(index: 127, cal: 100, image: "images/Lunch/paleo-linguine-clams.jpg", name: "Linguine Clams"),
  Foods(index: 128, cal: 100, image: "images/Lunch/paleo-meatball-soup.jpg", name: "Meatballs Soup"),
  Foods(index: 129, cal: 100, image: "images/Lunch/paleo-oven-fried-chicken.jpg", name: "Oven Fried Chicken"),
  Foods(index: 130, cal: 100, image: "images/Dessert/almond-kulfi.jpg", name: "Almond Kulfi"),
  Foods(index: 131, cal: 100, image: "images/Lunch/paleo-scallops-with-chimichurri.jpg", name: "Scallops With Chimichurri"),
  Foods(index: 132, cal: 100, image: "images/Lunch/paleo-seared-tuna-tacos.jpg", name: "Seared Tuna Tacos"),
  Foods(index: 133, cal: 100, image: "images/Lunch/paleo-steak-eggs-chimichurri.jpg", name: "Steak with Eggs"),
  Foods(index: 134, cal: 100, image: "images/Lunch/paleo-swedish-meatballs.jpg", name: "Swedish Meatballs"),
  Foods(index: 135, cal: 100, image: "images/Lunch/paleo-sweet-spicy-beef.jpg", name: "Spicy Beef"),
  Foods(index: 136, cal: 100, image: "images/Lunch/vegetarian-artichoke-dip-1.jpg", name: "Veggie Artichoke Dip"),
  Foods(index: 137, cal: 100, image: "images/Lunch/vegetarian-bruschetta-two-ways.jpg", name: "Veggie Bruschetta"),
  Foods(index: 138, cal: 100, image: "images/Lunch/vegetarian-butternut-ravioli-sage-brown-butter.jpg", name: "Butternut Ravioli"),
  Foods(index: 139, cal: 100, image: "images/Lunch/vegetarian-caprese-tomato-towers.jpg", name: "Carpese Tomato Tower"),
  Foods(index: 140, cal: 100, image: "images/Lunch/vegetarian-green-bean-casserole.jpg", name: "Green Bean Casserole"),
  Foods(index: 141, cal: 100, image: "images/Lunch/vegetarian-grilled-mexican-style-corn.jpg", name: "Grilled Mexican Corn"),
  Foods(index: 141, cal: 100, image: "images/Lunch/vegetarian-melted-brie-vegetables.jpg", name: "Melted brie Vegetables"),
  Foods(index: 143, cal: 100, image: "images/Lunch/vegetarian-warm-goat-cheese-salad.jpg", name: "Goat Cheese Salad"),
  Foods(index: 144, cal: 100, image: "images/Lunch/Whole30-Green-Machine-Casserole.jpg", name: "Machine Casserole"),
  Foods(index: 145, cal: 100, image: "images/Dessert/Whole30-Lemon-Cake.jpg", name: "Lemon Cake"),
  Foods(index: 146, cal: 100, image: "images/Lunch/Black-Pepper-Soy-Chicken-Wings.jpg", name: "Chicken Wings"),
  Foods(index: 147, cal: 100, image: "images/Lunch/garlic-wings.jpg", name: "Garlic Wings"),
  Foods(index: 148, cal: 100, image: "images/Lunch/vegan-sausage-sheet-pan.jpg", name: "Sausage Sheet Pan"),
  Foods(index: 149, cal: 100, image: "images/Dessert/Apple-Pie.jpg", name: "Apple Pie"),
  Foods(index: 150, cal: 100, image: "images/Dessert/baked-ricotta-cake.jpg", name: "Ricotta Cake"),
  Foods(index: 151, cal: 100, image: "images/Dessert/banana-chocolate-chip-muffins.jpg", name: "Chocolate Muffin"),
  Foods(index: 152, cal: 100, image: "images/Dessert/banoffee-cream-pudding.jpg", name: "Banoffee Pudding"),
  Foods(index: 153, cal: 100, image: "images/Dessert/biscoff-cookie-butter-ice-cream.jpg", name: "Cookie butter IceCream"),
  Foods(index: 154, cal: 100, image: "images/Dessert/Black-Forest.jpg", name: "Black Forest"),
  Foods(index: 155, cal: 100, image: "images/Dessert/blueberry-icecream.jpg", name: "Blueberry IceCream"),
  Foods(index: 156, cal: 100, image: "images/Dessert/Breakfast-Muffins.jpg", name: "Breakfast Muffins"),
  Foods(index: 157, cal: 100, image: "images/Dessert/burnt-butter-almond-and-honey-cake.jpg", name: "Almond-n-Honey Cake"),
  Foods(index: 158, cal: 100, image: "images/Dessert/Butterscotch-Pudding-Torte.jpg", name: "Butterscotch Pudding"),
  Foods(index: 159, cal: 100, image: "images/Dessert/chocolate-and-ginger-teacake.jpg", name: "Ginger TeaCake"),
  Foods(index: 160, cal: 100, image: "images/Dessert/chocolate-brownies-.jpg", name: "Chocolate Brownies"),
  Foods(index: 161, cal: 100, image: "images/Dessert/Chocolate-Chunk-Muffins.jpg", name: "Chunk Muffins"),
  Foods(index: 162, cal: 100, image: "images/Dessert/chocolate-ice-cream.jpg", name: "Chocolate IceCream"),
  Foods(index: 163, cal: 100, image: "images/Dessert/chocolate-truffle.jpg", name: "Chocolate Truffle"),
  Foods(index: 164, cal: 100, image: "images/Dessert/coconut-yoghurt-cake.jpg", name: "Coconut Yoghurt Cake"),
  Foods(index: 165, cal: 100, image: "images/Dessert/cointreau-souffle.jpg", name: "Cointreau Souffle"),
  Foods(index: 166, cal: 100, image: "images/Dessert/Cookies-and-Cream-Oreo-Brownies.jpg", name: "Oreo Brownies"),
  Foods(index: 167, cal: 100, image: "images/Dessert/Dark-Chocolate-Cheesecake.jpg", name: "Chocolate CheeseCake"),
  Foods(index: 168, cal: 100, image: "images/Dessert/easy-peasy-lemon-meringue-pie.jpg", name: "Lemon Meringue Pie"),
  Foods(index: 169, cal: 100, image: "images/Dessert/favorite-pecan-pie.jpg", name: "Pecan Pie"),
  Foods(index: 170, cal: 100, image: "images/Dessert/First-Place-Coconut-Macaroon.jpg", name: "Coconut Macaroon"),
  Foods(index: 171, cal: 100, image: "images/Dessert/French-Silk-Pie.jpg", name: "French Silk Pie"),
  Foods(index: 172, cal: 100, image: "images/Dessert/Fresh-Strawberry-Cupcakes.jpg", name: "Strawberry CupCake"),
  Foods(index: 173, cal: 100, image: "images/Dessert/Fudgiest-Brownies.jpg", name: "Fudge brownies"),
  Foods(index: 174, cal: 100, image: "images/Dessert/Fried-Apples.jpg", name: "Fried Apples"),
  Foods(index: 175, cal: 100, image: "images/Dessert/Leftover-Rice-Pudding.jpg", name: "Rice Pudding"),
  Foods(index: 176, cal: 100, image: "images/Dessert/lemon_blueberry_muffins.jpg", name: "Lemon Blueberr Muffins"),
  Foods(index: 177, cal: 100, image: "images/Dessert/Lemon-misu.jpg", name: "Lemon Misu"),
  Foods(index: 178, cal: 100, image: "images/Dessert/Lemon-Pound-Cake.jpg", name: "Lemon Pound Cake"),
  Foods(index: 179, cal: 100, image: "images/Dessert/Linzer-Cookies.jpg", name: "Linzer Cookie"),
  Foods(index: 180, cal: 100, image: "images/Dessert/mint-cheesecake-swirl-brownies.jpg", name: "Cheesecake Brownies"),
  Foods(index: 181, cal: 100, image: "images/Dessert/New-York-Style-Cheesecake.jpg", name: "NewYork Cheesecake"),
  Foods(index: 182, cal: 100, image: "images/Dessert/no-bake-tiramisu-cheesecake.jpeg", name: "Tiramisu Cheesecake"),
  Foods(index: 183, cal: 100, image: "images/Dessert/oreo-cheesecake.jpg", name: "Oreo Cheesecake"),
  Foods(index: 184, cal: 100, image: "images/Dessert/Peanut-Butter-Chocolate-Dessert.jpg", name: "Peanut Butter Chocolate"),
  Foods(index: 185, cal: 100, image: "images/Dessert/peanut-butter-pie.jpg", name: "Peanut Butter Pie"),
  Foods(index: 186, cal: 100, image: "images/Dessert/pecan-baklava-roll.jpg", name: "Pecan Baklava Roll"),
  Foods(index: 187, cal: 100, image: "images/Dessert/pecan-chocolate-bread-and-butter-pudding.jpg", name: "Bread and Butter Pudding"),
  Foods(index: 188, cal: 100, image: "images/Dessert/Pineapple-Upside-Down-Cake.jpg", name: "Pineapple Cake"),
  Foods(index: 189, cal: 100, image: "images/Dessert/pistachio-phirni.jpg", name: "Pistachio"),
  Foods(index: 190, cal: 100, image: "images/Dessert/pumpkin-chocolate-chip-muffins.jpg", name: "Pumpkin Chocolate Muffins"),
  Foods(index: 191, cal: 100, image: "images/Dessert/Pumpkin-Pie.jpg", name: "Pumpkin Pie"),
  Foods(index: 192, cal: 100, image: "images/Dessert/red-velvet-cake.jpg", name: "Red Velvet Cake"),
  Foods(index: 193, cal: 100, image: "images/Dessert/red-velvet-kiss-cookies.jpg", name: "Red Velvet Cookie"),
  Foods(index: 194, cal: 100, image: "images/Dessert/Skillet-Brownies-.jpg", name: "Skillet Brownies"),
  Foods(index: 195, cal: 100, image: "images/Dessert/Sprinkle-Sugar-Cookies.jpg", name: "Sprinkle Sugar Cookie"),
  Foods(index: 196, cal: 100, image: "images/Dessert/strawberry-dark-chocoloate-truffle-cake.jpg", name: "Strawberry Truffle Cake"),
  Foods(index: 197, cal: 100, image: "images/Dessert/Strawberry-Trifle.jpg", name: "Strawberry Trifle"),
  Foods(index: 198, cal: 100, image: "images/Dessert/Sugar-Cream-Pie.jpg", name: "Sugar Cream Pie"),
  Foods(index: 199, cal: 100, image: "images/Dessert/tart-al-limone.jpg", name: "Tart-al-Limone"),
  Foods(index: 200, cal: 100, image: "images/Dessert/Tres-Leches-Cake.jpg", name: "Tres Leches Cake"),
  Foods(index: 201, cal: 100, image: "images/Dessert/Vanilla-Cupcakes.jpg", name: "Vanilla Cupcake"),
  Foods(index: 202, cal: 100, image: "images/Dessert/Vanilla-Ice-Cream.jpg", name: "Vanilla IceCream"),
  Foods(index: 203, cal: 100, image: "images/Dessert/Vanilla-Meringue-Cookies.jpg", name: "Vanilla Cookie"),
  Foods(index: 204, cal: 100, image: "images/Dessert/White-Chocolate-Raspberry-Cheesecake.jpg", name: "Raspberry Cheesecake"),
  Foods(index: 205, cal: 100, image: "images/BreakFast/40-second-omelet.jpg", name: "40 Second Omelet"),
  Foods(index: 206, cal: 100, image: "images/BreakFast/aloo-paratha.jpg", name: "Aloo Paratha"),
  Foods(index: 207, cal: 100, image: "images/BreakFast/amlet.jpg", name: "Omelet"),
  Foods(index: 208, cal: 100, image: "images/BreakFast/banana-pancakes.jpg", name: "Banana Pancakes"),
  Foods(index: 209, cal: 100, image: "images/BreakFast/bbq-sandwiches.jpg", name: "BBQ Sandwich"),
  Foods(index: 210, cal: 100, image: "images/BreakFast/biscuits.jpg", name: "Biscuits"),
  Foods(index: 211, cal: 100, image: "images/BreakFast/breakfast-pizza.jpg", name: "BreakFast Pizza"),
  Foods(index: 212, cal: 100, image: "images/BreakFast/cake-rusk.jpg", name: "Cake Rusk"),
  Foods(index: 213, cal: 100, image: "images/BreakFast/cheese-omelete.jpg", name: "Cheese Omelet"),
  Foods(index: 214, cal: 100, image: "images/BreakFast/chicken-cheese-paratha.jpg", name: "Chicken Paratha"),
  Foods(index: 215, cal: 100, image: "images/BreakFast/croissants.jpg", name: "Croissant"),
  Foods(index: 216, cal: 100, image: "images/BreakFast/dal-puri.jpg", name: "Dall Puri"),
  Foods(index: 217, cal: 100, image: "images/BreakFast/easy-egg-omlete.jpg", name: "Egg Omelet"),
  Foods(index: 218, cal: 100, image: "images/BreakFast/egg-bhurji.jpg", name: "Anda Bhurji"),
  Foods(index: 219, cal: 100, image: "images/BreakFast/egg-fried-bread.jpg", name: "Egg Fried Bread"),
  Foods(index: 220, cal: 100, image: "images/BreakFast/egg-muffins.jpg", name: "Egg Muffins"),
  Foods(index: 221, cal: 100, image: "images/BreakFast/egg-salan.jpg", name: "Egg Salan"),
  Foods(index: 222, cal: 100, image: "images/BreakFast/feather-light-pancakes.jpg", name: "Light Pancake"),
  Foods(index: 223, cal: 100, image: "images/BreakFast/fluffy-omelt.jpg", name: "Fluffy Omelet"),
  Foods(index: 224, cal: 100, image: "images/BreakFast/french-omelllete.jpg", name: "French Omelet"),
  Foods(index: 225, cal: 100, image: "images/BreakFast/french-toast.jpg", name: "French Toast"),
  Foods(index: 226, cal: 100, image: "images/BreakFast/gobhi-paratha.jpg", name: "Gobhi Paratha"),
  Foods(index: 227, cal: 100, image: "images/BreakFast/greek-omelette.jpg", name: "Greek Omelet"),
  Foods(index: 228, cal: 100, image: "images/BreakFast/kashmiri-hareesa.jpg", name: "Kasmiri Hareesa"),
  Foods(index: 229, cal: 100, image: "images/BreakFast/khagina.jpg", name: "Khagina"),
  Foods(index: 230, cal: 100, image: "images/BreakFast/low-carb-vanilla-bourbon-french-toast.jpg", name: "Vanilla Toast"),
  Foods(index: 231, cal: 100, image: "images/BreakFast/mango-jam.jpg", name: "Mango Jam"),
  Foods(index: 232, cal: 100, image: "images/BreakFast/meethay-pakoray.jpg", name: "Meethay Pakoray"),
  Foods(index: 233, cal: 100, image: "images/BreakFast/meethi-roti.jpg", name: "Meethi Roti"),
  Foods(index: 234, cal: 100, image: "images/BreakFast/mexican-omelet.jpg", name: "Mexican Omelet"),
  Foods(index: 235, cal: 100, image: "images/BreakFast/overnight-baked-french-toast.jpg", name: "Overnight Toast"),
  Foods(index: 236, cal: 100, image: "images/BreakFast/pizza-paratha.jpg", name: "Pizza Paratha"),
  Foods(index: 237, cal: 100, image: "images/BreakFast/prawn-omelette.jpg", name: "Prawn Omelet"),
  Foods(index: 238, cal: 100, image: "images/BreakFast/rainbow-omelette.jpg", name: "Rainbow Omelet"),
  Foods(index: 239, cal: 100, image: "images/BreakFast/simple-cheese-omelette.jpg", name: "Cheese Omelet"),
  Foods(index: 240, cal: 100, image: "images/BreakFast/soybean.jpg", name: "Soybean"),
  Foods(index: 241, cal: 100, image: "images/BreakFast/stuffed-eggs.jpg", name: "Stuffed eggs"),
  Foods(index: 242, cal: 100, image: "images/BreakFast/syrian-bread.jpg", name: "Syrian Bread"),
  Foods(index: 243, cal: 100, image: "images/BreakFast/white-bread.jpg", name: "White Bread"),
  Foods(index: 244, cal: 100, image: "images/appetizer/authentic-chinese-egg-rolls-from-a-chinese-person.jpg", name: "Chinese Egg Rolls"),
  Foods(index: 245, cal: 100, image: "images/appetizer/Baked-Brie-with-Caramelized-Onions.jpg", name: "Brie with Caramelized Onions"),
  Foods(index: 246, cal: 100, image: "images/appetizer/banana-nutella-crepe.jpg", name: "Banana Nutella Crepe"),
  Foods(index: 247, cal: 100, image: "images/appetizer/beef-taquitos.jpg", name: "Beef Taquitos"),
  Foods(index: 248, cal: 100, image: "images/appetizer/best-ever-jalapeno-poppers.jpg", name: "Japlapeno Poppers"),
  Foods(index: 249, cal: 100, image: "images/appetizer/Brie-Cheese-Appetizer.jpg", name: "Brie Cheese Appetizer"),
  Foods(index: 250, cal: 100, image: "images/appetizer/Brie-Cups.jpg", name: "Brie Cups"),
  Foods(index: 251, cal: 100, image: "images/appetizer/Cheddar-Cheese-Nippers.jpg", name: "Cheese Nippers"),
  Foods(index: 252, cal: 100, image: "images/appetizer/Chicken-Salad-Wanton-cups.jpg", name: "Chicken Salad Cups"),
  Foods(index: 253, cal: 100, image: "images/appetizer/chocolate_chip_cookies1.jpg", name: "Chocolate chip Cookie"),
  Foods(index: 254, cal: 100, image: "images/appetizer/crab-cakes.jpg", name: "Crab Cake"),
  Foods(index: 255, cal: 100, image: "images/appetizer/crispy-wonton-chips.jpg", name: "Crispy Wonton Chips"),
  Foods(index: 256, cal: 100, image: "images/appetizer/Figs-and-Toasted-Almonds-Brie.jpg", name: "Toasted Almond Brie"),
  Foods(index: 257, cal: 100, image: "images/appetizer/fried-burrata-ball.jpg", name: "Fried Burrata Balls"),
  Foods(index: 258, cal: 100, image: "images/appetizer/Garlicky-Baked-Brie.jpg", name: "Garlicky Brie"),
  Foods(index: 259, cal: 100, image: "images/appetizer/Greek-Meatballs.jpg", name: "Greek Meatballs"),
  Foods(index: 260, cal: 100, image: "images/appetizer/Grilled-Sandwich.jpg", name: "Grilled Sandwich"),
  Foods(index: 261, cal: 100, image: "images/appetizer/jalapeno-poppers.jpg", name: "Jalapeno Poppers"),
  Foods(index: 262, cal: 100, image: "images/appetizer/jamaican-saltfish-fritters.jpg", name: "Jamaican Salt Fish"),
  Foods(index: 263, cal: 100, image: "images/appetizer/Kettle-Corn.jpg", name: "Kettle Corn"),
  Foods(index: 264, cal: 100, image: "images/appetizer/Lavosh.jpg", name: "Lavosh"),
  Foods(index: 265, cal: 100, image: "images/appetizer/Masala-Wings.jpg", name: "Masla Wings"),
  Foods(index: 266, cal: 100, image: "images/appetizer/paleo-plum-muffins.jpg", name: "Plum Muffins"),
  Foods(index: 267, cal: 100, image: "images/appetizer/potato-chips.jpg", name: "Patato Chips"),
  Foods(index: 268, cal: 100, image: "images/appetizer/Pulled-chicken-sandwich.png", name: "Chicken Sandwich"),
  Foods(index: 269, cal: 100, image: "images/appetizer/Pulled-Pork-Masa-Cakes.jpg", name: "Pork Masa Cake"),
  Foods(index: 270, cal: 100, image: "images/appetizer/skewers-with-lemon-chive.jpg", name: "Skewers with Lemon Chive"),
  Foods(index: 271, cal: 100, image: "images/appetizer/smoked-salmon-rolls.jpg", name: "Smoked Salmon Rolls"),
  Foods(index: 272, cal: 100, image: "images/appetizer/Spinach-Puff-Pastry-Rolls.jpg", name: "Pastry Rolls"),
  Foods(index: 273, cal: 100, image: "images/appetizer/Swet-Potato-Nachos.jpg", name: "Potato Nachos"),
  Foods(index: 274, cal: 100, image: "images/appetizer/Tuna-Potato-Croquettes.jpg", name: "Tuna Potato Croquettes"),
  // Foods(index: 275, cal: 100, image: "images/appetizer/.jpg", name: ""),
  // Foods(index: 276, cal: 100, image: "images/appetizer/.jpg", name: ""),
  // Foods(index: 277, cal: 100, image: "images/appetizer/.jpg", name: ""),
  // Foods(index: 278, cal: 100, image: "images/appetizer/.jpg", name: ""),
  // Foods(index: 279, cal: 100, image: "images/appetizer/.jpg", name: ""),
  // Foods(index: 280, cal: 100, image: "images/appetizer/.jpg", name: ""),
  // Foods(index: 281, cal: 100, image: "images/appetizer/.jpg", name: ""),
  // Foods(index: 282, cal: 100, image: "images/appetizer/.jpg", name: ""),
  // Foods(index: 283, cal: 100, image: "images/appetizer/.jpg", name: ""),
  // Foods(index: 284, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 285, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 286, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 287, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 288, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 289, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 290, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 291, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 292, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 293, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 294, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 295, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 296, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 297, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 298, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 299, cal: 100, image: "images/.jpg", name: ""),
  // Foods(index: 300, cal: 100, image: "images/.jpg", name: ""),
];


const lunchList = const [
  Foods(index: 1, cal: 100, image: "images/Lunch/aloo-gobi.jpg", name: "Aloo Gobi"),
  Foods(index: 2, cal: 100, image: "images/Lunch/aloo-palak.jpg", name: "Aloo Palak"),
  Foods(index: 3, cal: 100, image: "images/Lunch/Pakistani-chowmein-noodle.jpg", name: "Chowmein"),
  Foods(index: 4, cal: 100, image: "images/Lunch/Channa-Dal.jpg", name: "Channa Dal"),
  Foods(index: 5, cal: 100, image: "images/Lunch/Chapli-Kabab.jpg", name: "Chapli Kabab"),
  Foods(index: 6, cal: 100, image: "images/Lunch/Chicken-Baryani.jpg", name: "Chicken Baryani"),
  Foods(index: 7, cal: 100, image: "images/Lunch/Chicken-Chargha.jpg", name: "Chicken Chargha"),
  Foods(index: 8, cal: 100, image: "images/Lunch/Chicken-Kofta.jpg", name: "Chicken Kofta"),
  Foods(index: 9, cal: 100, image: "images/Lunch/Chicken-Korma.jpg", name: "Chicken Korama"),
  Foods(index: 10, cal: 100, image: "images/Lunch/Chicken-Malai-Tikka.jpg", name: "Malai Tikka"),
  Foods(index: 11, cal: 100, image: "images/Lunch/Chicken-Parmesan-Slider-Bake.jpg", name: "Chicken Slider"),
  Foods(index: 12, cal: 100, image: "images/Lunch/Chicken-Tikka-Leg-Recipe.jpg", name: "Chicken Tikka"),
  Foods(index: 19, cal: 100, image: "images/Lunch/Grilled-Tomato-Peach-Pizza.jpg", name: "Peach Pizza"),
  Foods(index: 20, cal: 100, image: "images/Lunch/Balochi-tikka.jpg", name: "Balochi Tikka"),
  Foods(index: 22, cal: 100, image: "images/Lunch/Hot-Artichoke-Spinach-Dip.jpg", name: "Artichoke"),
  Foods(index: 23, cal: 100, image: "images/Lunch/keema-naan.jpg", name: "Keema Naan"),
  Foods(index: 26, cal: 100, image: "images/Lunch/Masoor-Daal.jpg", name: "Masoor Daal"),
  Foods(index: 28, cal: 100, image: "images/Lunch/Orange-Glazed-Meatballs.jpg", name: "Glazed Meatballs"),
  Foods(index: 33, cal: 100, image: "images/Lunch/Sarsoon-ka-saag.jpg", name: "Sarsoon Saag"),
  Foods(index: 34, cal: 100, image: "images/Lunch/seekh-kaba.jpg", name: "Seekh Kabab"),
  Foods(index: 35, cal: 100, image: "images/Lunch/shahi-tukda.jpg", name: "Shahi Tukda"),
  Foods(index: 37, cal: 100, image: "images/Lunch/Teriyaki-Meatballs.jpg", name: "Teriyaki Meatballs"),
  Foods(index: 38, cal: 100, image: "images/Lunch/Tuscan-Sausage-Bean-Dip.jpg", name: "Tuscan Bean"),
  Foods(index: 39, cal: 100, image: "images/Lunch/Yakhni-Pulao.jpg", name: "Yakhni Pulao"),
  Foods(index: 40, cal: 100, image: "images/Lunch/air-fryer-breaded-pork-chop-1.jpg", name: "Pork Chop"),
  Foods(index: 42, cal: 100, image: "images/Lunch/avocado-crisps.jpg", name: "Avocado Crisps"),
  Foods(index: 44, cal: 100, image: "images/Lunch/beef-skewers.jpg", name: "Beef Skewers"),
  Foods(index: 45, cal: 100, image: "images/Lunch/beef-stew.jpg", name: "Beef Stew"),
  Foods(index: 50, cal: 100, image: "images/Lunch/Crock-pot-beef-ragu-recipe.jpg", name: "Crock Pot Beef"),
  Foods(index: 51, cal: 100, image: "images/Lunch/crock-pot-chicke-noodle-soup-recipe.jpg", name: "Chicken Noodle"),
  Foods(index: 53, cal: 100, image: "images/Lunch/gluten-free-chicken-fingers-chipotle-honey.jpg", name: "Chicken fingers"),
  Foods(index: 54, cal: 100, image: "images/Lunch/gluten-free-crispy-rosemary-potatoes.jpg", name: "Rosemary Potatoes"),
  Foods(index: 55, cal: 100, image: "images/Lunch/grilled-cheese-sauteed-mushrooms.jpg", name: "Cheese Mushrooms"),
  Foods(index: 56, cal: 100, image: "images/Lunch/grilled-chicken-salad-cranberries-avacado-goat-cheese.jpg", name: "Chicken Salad"),
  Foods(index: 57, cal: 100, image: "images/Lunch/healthy-barbecue-chicken-pizza.jpg", name: "Barbecue Pizza"),
  Foods(index: 58, cal: 100, image: "images/Lunch/healthy-black-bean-omelet.jpg", name: "Black Bean Omelet"),
  Foods(index: 60, cal: 100, image: "images/Lunch/healthy-blueberry-peach-cobbler.jpg", name: "Blueberry Cobbler"),
  Foods(index: 61, cal: 100, image: "images/Lunch/healthy-butternut-squash-soup.jpg", name: "Butternut Squash"),
  Foods(index: 62, cal: 100, image: "images/Lunch/healthy-caprese-sandwich.jpg", name: "Carprese Sandwich"),
  Foods(index: 63, cal: 100, image: "images/Lunch/healthy-chicken-burger-sundried-tomato-aioli.jpg", name: "Burger with Sundried Tomato"),
  Foods(index: 64, cal: 100, image: "images/Lunch/healthy-chicken-fried-rice.jpg", name: "Chicken Fried Rice"),
  Foods(index: 65, cal: 100, image: "images/Lunch/healthy-chicken-under-a-brick.jpg", name: "Chicken Brick"),
  Foods(index: 66, cal: 100, image: "images/Lunch/healthy-chipotle-shrimp-quesadilla.jpg", name: "Shrimp Quesadilla"),
  Foods(index: 67, cal: 100, image: "images/Lunch/healthy-egg-sandwich-with-pastrami-and-swiss-recipe.jpg", name: "Sandwich with Pastrami"),
  Foods(index: 68, cal: 100, image: "images/Lunch/healthy-fiery-buffalo-wings.jpg", name: "Fiery Buffalo Wings"),
  Foods(index: 69, cal: 100, image: "images/Lunch/healthy-grilled-calamari-salad.jpg", name: "Grilled Calamari"),
  Foods(index: 70, cal: 100, image: "images/Lunch/healthy-grilled-mahi-mahi-salsa-verde.jpg", name: "Mahi Salsa Verde"),
  Foods(index: 71, cal: 100, image: "images/Lunch/healthy-grilled-veggie-wrap.jpg", name: "Grilled Veggie Wrap"),
  Foods(index: 73, cal: 100, image: "images/Lunch/healthy-italian-tuna-melt.jpg", name: "Italian Tuna Melt"),
  Foods(index: 74, cal: 100, image: "images/Lunch/healthy-loaded-alfredo-chicken-vegetables.jpg", name: "Chicken Vegetable"),
  Foods(index: 75, cal: 100, image: "images/Lunch/healthy-meatballs-polenta.jpg", name: "Meatballs Polenta"),
  Foods(index: 79, cal: 100, image: "images/Lunch/healthy-pork-tenderloin-grilled-pineapple-salsa.jpg", name: "Tenderloin Pork"),
  Foods(index: 80, cal: 100, image: "images/Lunch/healthy-red-pepper-alfredo.jpg", name: "Red Pepper Alfredo"),
  Foods(index: 81, cal: 100, image: "images/Lunch/healthy-smokey-deviled-eggs.jpg", name: "Smokey Eggs"),
  Foods(index: 82, cal: 100, image: "images/Lunch/healthy-spaghetti-spicy-tomato-sauce.jpg", name: "Spaghetti Tomato Sauce"),
  Foods(index: 84, cal: 100, image: "images/Lunch/healthy-ultimate-club-sandwich-with-super-mayo.jpg", name: "Club Sandwich"),
  Foods(index: 85, cal: 100, image: "images/Lunch/healthy-waffles-ham-egg.jpg", name: "Waffles Ham Egg"),
  Foods(index: 88, cal: 100, image: "images/Lunch/instant-pot-lemon-chicken-2.jpg", name: "Instant Pot Chicken"),
  Foods(index: 89, cal: 100, image: "images/Lunch/instant-pot-shimp-and-broccoli-4-1.jpg", name: "Shrimp and Broccoli"),
  Foods(index: 90, cal: 100, image: "images/Lunch/Instant-Pot-steak-fajitas-2.jpg", name: "Steak Fajitas"),
  Foods(index: 91, cal: 100, image: "images/Lunch/italian-panini-provolone-peppers-arugula.jpg", name: "Italian Burger"),
  Foods(index: 92, cal: 100, image: "images/Lunch/keto-bacon-cheese-sandwich.jpg", name: "Cheese Sandwich"),
  Foods(index: 95, cal: 100, image: "images/Lunch/keto-pizza-cups-overhead.jpg", name: "Pizza Cups"),
  Foods(index: 96, cal: 100, image: "images/Lunch/keto-roast-chicken.jpg", name: "Roast Chicken"),
  Foods(index: 97, cal: 100, image: "images/Lunch/keto-shredded-pork-shoulder.jpg", name: "Shredded Pork"),
  Foods(index: 98, cal: 100, image: "images/Lunch/keto-zucchini-noodles.jpg", name: "Zucchini Noodles"),
  Foods(index: 99, cal: 100, image: "images/Lunch/lentil-veggie-tots-hot-dish-1.jpg", name: "Lentil Veggie Tots"),
  Foods(index: 101, cal: 100, image: "images/Lunch/low-calorie-bolognese-fettuccine-turkey.jpg", name: "Fettuccine Turkey"),
  Foods(index: 102, cal: 100, image: "images/Lunch/low-calorie-cheesesteak-sandwich.jpg", name: "CheeseStack Sandwich"),
  Foods(index: 103, cal: 100, image: "images/Lunch/low-calorie-chicken-mole-enchiladas.jpg", name: "Chicken Role"),
  Foods(index: 105, cal: 100, image: "images/Lunch/low-calorie-grilled-caesar-salad.jpg", name: "Caesar Salad"),
  Foods(index: 106, cal: 100, image: "images/Lunch/low-calorie-huevos-rancheros.jpg", name: "Huevos Rancheros"),
  Foods(index: 107, cal: 100, image: "images/Lunch/low-calorie-ricotta-cheesecake-warm-blueberries.jpg", name: "Ricotta CheeseCake"),
  Foods(index: 108, cal: 100, image: "images/Lunch/low-calorie-spinach-ham-quiche.jpg", name: "Spinach Ham"),
  Foods(index: 111, cal: 100, image: "images/Lunch/mediterranean-tofu-veggiescramble.jpg", name: "Tofu Veggie Scramble"),
  Foods(index: 113, cal: 100, image: "images/Lunch/pistachio-cheese-ball-3.jpg", name: "Pistachio Ball"),
  Foods(index: 114, cal: 100, image: "images/Lunch/plant-based-cali-veggie-burger-with-egg.jpg", name: "Veggie Burger"),
  Foods(index: 116, cal: 100, image: "images/Lunch/pumpkin-mole-chili.jpg", name: "Pumpkin Chili"),
  Foods(index: 118, cal: 100, image: "images/Lunch/seared-ginger-cumin-swordfish-blueberry-avocado-salsa.png", name: "SwordFish with Blueberry"),
  Foods(index: 119, cal: 100, image: "images/Lunch/shakshuka-paleo-casserole.jpg", name: "Paleo Casserole"),
  Foods(index: 120, cal: 100, image: "images/Lunch/sheet-pan-pork-chops.jpg", name: "Pan Pork Chops"),
  Foods(index: 122, cal: 100, image: "images/Lunch/taco-pasta.jpg", name: "Taco Pasta"),
  Foods(index: 123, cal: 100, image: "images/Lunch/vegan-sausage-sheet-pan.jpg", name: "Vegan Sausage"),
  Foods(index: 124, cal: 100, image: "images/Lunch/paleo-asian-chicken-meatballs.jpg", name: "Asian Chicken Meatballs"),
  Foods(index: 125, cal: 100, image: "images/Lunch/paleo-chicken-pot-stickers.jpg", name: "Chicken Pot Skickers"),
  Foods(index: 126, cal: 100, image: "images/Lunch/paleo-grilled-chicken-pinapple-sandwich.jpg", name: "Grilled Chicken Sandwich"),
  Foods(index: 127, cal: 100, image: "images/Lunch/paleo-linguine-clams.jpg", name: "Linguine Clams"),
  Foods(index: 128, cal: 100, image: "images/Lunch/paleo-meatball-soup.jpg", name: "Meatballs Soup"),
  Foods(index: 129, cal: 100, image: "images/Lunch/paleo-oven-fried-chicken.jpg", name: "Oven Fried Chicken"),
  Foods(index: 131, cal: 100, image: "images/Lunch/paleo-scallops-with-chimichurri.jpg", name: "Scallops With Chimichurri"),
  Foods(index: 132, cal: 100, image: "images/Lunch/paleo-seared-tuna-tacos.jpg", name: "Seared Tuna Tacos"),
  Foods(index: 133, cal: 100, image: "images/Lunch/paleo-steak-eggs-chimichurri.jpg", name: "Steak with Eggs"),
  Foods(index: 134, cal: 100, image: "images/Lunch/paleo-swedish-meatballs.jpg", name: "Swedish Meatballs"),
  Foods(index: 135, cal: 100, image: "images/Lunch/paleo-sweet-spicy-beef.jpg", name: "Spicy Beef"),
  Foods(index: 136, cal: 100, image: "images/Lunch/vegetarian-artichoke-dip-1.jpg", name: "Veggie Artichoke Dip"),
  Foods(index: 137, cal: 100, image: "images/Lunch/vegetarian-bruschetta-two-ways.jpg", name: "Veggie Bruschetta"),
  Foods(index: 138, cal: 100, image: "images/Lunch/vegetarian-butternut-ravioli-sage-brown-butter.jpg", name: "Butternut Ravioli"),
  Foods(index: 139, cal: 100, image: "images/Lunch/vegetarian-caprese-tomato-towers.jpg", name: "Carpese Tomato Tower"),
  Foods(index: 140, cal: 100, image: "images/Lunch/vegetarian-green-bean-casserole.jpg", name: "Green Bean Casserole"),
  Foods(index: 141, cal: 100, image: "images/Lunch/vegetarian-grilled-mexican-style-corn.jpg", name: "Grilled Mexican Corn"),
  Foods(index: 141, cal: 100, image: "images/Lunch/vegetarian-melted-brie-vegetables.jpg", name: "Melted brie Vegetables"),
  Foods(index: 143, cal: 100, image: "images/Lunch/vegetarian-warm-goat-cheese-salad.jpg", name: "Goat Cheese Salad"),
  Foods(index: 144, cal: 100, image: "images/Lunch/Whole30-Green-Machine-Casserole.jpg", name: "Machine Casserole"),
  Foods(index: 146, cal: 100, image: "images/Lunch/Black-Pepper-Soy-Chicken-Wings.jpg", name: "Chicken Wings"),
  Foods(index: 147, cal: 100, image: "images/Lunch/garlic-wings.jpg", name: "Garlic Wings"),
  Foods(index: 148, cal: 100, image: "images/Lunch/vegan-sausage-sheet-pan.jpg", name: "Sausage Sheet Pan"),
];

const dessertList = const [
  Foods(index: 13, cal: 100, image: "images/Dessert/Chocolate-Biscuit-Pudding.jpg", name: "Pudding"),
  Foods(index: 14, cal: 100, image: "images/Dessert/CHOCOLATE-CHIP-COOKIES.jpg", name: "Cookies"),
  Foods(index: 18, cal: 100, image: "images/Dessert/gajar-halwa.jpg", name: "Gajar Halwa"),
  Foods(index: 24, cal: 100, image: "images/Dessert/lab-e-shireen.jpg", name: "Lab-e-Shireen"),
  Foods(index: 25, cal: 100, image: "images/Dessert/mango-kulfi.jpg", name: "Mango Kulfi"),
  Foods(index: 30, cal: 100, image: "images/Dessert/pancakes.jpg", name: "Pancakes"),
  Foods(index: 32, cal: 100, image: "images/Dessert/Rice-Kheer.jpg", name: "Rice Kherr"),
  Foods(index: 36, cal: 100, image: "images/Dessert/sooji-halwa.jpg", name: "Sooji Halwa"),
  Foods(index: 46, cal: 100, image: "images/Dessert/blood-orange-beet-smoothie.jpg", name: "Beet Smoothie"),
  Foods(index: 47, cal: 100, image: "images/Dessert/chocolate-pudding-olive-oil-sea-salt.jpg", name: "Chocolate Pudding"),
  Foods(index: 52, cal: 100, image: "images/Dessert/fudgy-pumpkin-brownie-bites.jpg", name: "Fudge Pumpkin"),
  Foods(index: 76, cal: 100, image: "images/Dessert/healthy-oatmeal–chocolate-chip-cookies.jpg", name: "Oatmeal Chocolate"),
  Foods(index: 100, cal: 100, image: "images/Dessert/low-calorie-apple-pie-crunch-topping.jpg", name: "Apple Pie"),
  Foods(index: 104, cal: 100, image: "images/Dessert/low-calorie-fudgy-brownies.jpg", name: "Fudge Brownies"),
  Foods(index: 112, cal: 100, image: "images/Dessert/molten-chocolate-cake.jpg", name: "Molten Chocolate"),
  Foods(index: 115, cal: 100, image: "images/Dessert/protein-powder-pancakes.jpg", name: "Powder Pancake"),
  Foods(index: 117, cal: 100, image: "images/Dessert/raspberry-smoothie.jpg", name: "Raspberry Smoothie"),
  Foods(index: 130, cal: 100, image: "images/Dessert/almond-kulfi.jpg", name: "Almond Kulfi"),
  Foods(index: 145, cal: 100, image: "images/Dessert/Whole30-Lemon-Cake.jpg", name: "Lemon Cake"),
  Foods(index: 149, cal: 100, image: "images/Dessert/Apple-Pie.jpg", name: "Apple Pie"),
  Foods(index: 150, cal: 100, image: "images/Dessert/baked-ricotta-cake.jpg", name: "Ricotta Cake"),
  Foods(index: 151, cal: 100, image: "images/Dessert/banana-chocolate-chip-muffins.jpg", name: "Chocolate Muffin"),
  Foods(index: 152, cal: 100, image: "images/Dessert/banoffee-cream-pudding.jpg", name: "Banoffee Pudding"),
  Foods(index: 153, cal: 100, image: "images/Dessert/biscoff-cookie-butter-ice-cream.jpg", name: "Cookie butter IceCream"),
  Foods(index: 154, cal: 100, image: "images/Dessert/Black-Forest.jpg", name: "Black Forest"),
  Foods(index: 155, cal: 100, image: "images/Dessert/blueberry-icecream.jpg", name: "Blueberry IceCream"),
  Foods(index: 156, cal: 100, image: "images/Dessert/Breakfast-Muffins.jpg", name: "Breakfast Muffins"),
  Foods(index: 157, cal: 100, image: "images/Dessert/burnt-butter-almond-and-honey-cake.jpg", name: "Almond-n-Honey Cake"),
  Foods(index: 158, cal: 100, image: "images/Dessert/Butterscotch-Pudding-Torte.jpg", name: "Butterscotch Pudding"),
  Foods(index: 159, cal: 100, image: "images/Dessert/chocolate-and-ginger-teacake.jpg", name: "Ginger TeaCake"),
  Foods(index: 160, cal: 100, image: "images/Dessert/chocolate-brownies-.jpg", name: "Chocolate Brownies"),
  Foods(index: 161, cal: 100, image: "images/Dessert/Chocolate-Chunk-Muffins.jpg", name: "Chunk Muffins"),
  Foods(index: 162, cal: 100, image: "images/Dessert/chocolate-ice-cream.jpg", name: "Chocolate IceCream"),
  Foods(index: 163, cal: 100, image: "images/Dessert/chocolate-truffle.jpg", name: "Chocolate Truffle"),
  Foods(index: 164, cal: 100, image: "images/Dessert/coconut-yoghurt-cake.jpg", name: "Coconut Yoghurt Cake"),
  Foods(index: 165, cal: 100, image: "images/Dessert/cointreau-souffle.jpg", name: "Cointreau Souffle"),
  Foods(index: 166, cal: 100, image: "images/Dessert/Cookies-and-Cream-Oreo-Brownies.jpg", name: "Oreo Brownies"),
  Foods(index: 167, cal: 100, image: "images/Dessert/Dark-Chocolate-Cheesecake.jpg", name: "Chocolate CheeseCake"),
  Foods(index: 168, cal: 100, image: "images/Dessert/easy-peasy-lemon-meringue-pie.jpg", name: "Lemon Meringue Pie"),
  Foods(index: 169, cal: 100, image: "images/Dessert/favorite-pecan-pie.jpg", name: "Pecan Pie"),
  Foods(index: 170, cal: 100, image: "images/Dessert/First-Place-Coconut-Macaroon.jpg", name: "Coconut Macaroon"),
  Foods(index: 171, cal: 100, image: "images/Dessert/French-Silk-Pie.jpg", name: "French Silk Pie"),
  Foods(index: 172, cal: 100, image: "images/Dessert/Fresh-Strawberry-Cupcakes.jpg", name: "Strawberry CupCake"),
  Foods(index: 173, cal: 100, image: "images/Dessert/Fudgiest-Brownies.jpg", name: "Fudge brownies"),
  Foods(index: 174, cal: 100, image: "images/Dessert/Fried-Apples.jpg", name: "Fried Apples"),
  Foods(index: 175, cal: 100, image: "images/Dessert/Leftover-Rice-Pudding.jpg", name: "Rice Pudding"),
  Foods(index: 176, cal: 100, image: "images/Dessert/lemon_blueberry_muffins.jpg", name: "Lemon Blueberr Muffins"),
  Foods(index: 177, cal: 100, image: "images/Dessert/Lemon-misu.jpg", name: "Lemon Misu"),
  Foods(index: 178, cal: 100, image: "images/Dessert/Lemon-Pound-Cake.jpg", name: "Lemon Pound Cake"),
  Foods(index: 179, cal: 100, image: "images/Dessert/Linzer-Cookies.jpg", name: "Linzer Cookie"),
  Foods(index: 180, cal: 100, image: "images/Dessert/mint-cheesecake-swirl-brownies.jpg", name: "Cheesecake Brownies"),
  Foods(index: 181, cal: 100, image: "images/Dessert/New-York-Style-Cheesecake.jpg", name: "NewYork Cheesecake"),
  Foods(index: 182, cal: 100, image: "images/Dessert/no-bake-tiramisu-cheesecake.jpeg", name: "Tiramisu Cheesecake"),
  Foods(index: 183, cal: 100, image: "images/Dessert/oreo-cheesecake.jpg", name: "Oreo Cheesecake"),
  Foods(index: 184, cal: 100, image: "images/Dessert/Peanut-Butter-Chocolate-Dessert.jpg", name: "Peanut Butter Chocolate"),
  Foods(index: 185, cal: 100, image: "images/Dessert/peanut-butter-pie.jpg", name: "Peanut Butter Pie"),
  Foods(index: 186, cal: 100, image: "images/Dessert/pecan-baklava-roll.jpg", name: "Pecan Baklava Roll"),
  Foods(index: 187, cal: 100, image: "images/Dessert/pecan-chocolate-bread-and-butter-pudding.jpg", name: "Bread and Butter Pudding"),
  Foods(index: 188, cal: 100, image: "images/Dessert/Pineapple-Upside-Down-Cake.jpg", name: "Pineapple Cake"),
  Foods(index: 189, cal: 100, image: "images/Dessert/pistachio-phirni.jpg", name: "Pistachio"),
  Foods(index: 190, cal: 100, image: "images/Dessert/pumpkin-chocolate-chip-muffins.jpg", name: "Pumpkin Chocolate Muffins"),
  Foods(index: 191, cal: 100, image: "images/Dessert/Pumpkin-Pie.jpg", name: "Pumpkin Pie"),
  Foods(index: 192, cal: 100, image: "images/Dessert/red-velvet-cake.jpg", name: "Red Velvet Cake"),
  Foods(index: 193, cal: 100, image: "images/Dessert/red-velvet-kiss-cookies.jpg", name: "Red Velvet Cookie"),
  Foods(index: 194, cal: 100, image: "images/Dessert/Skillet-Brownies-.jpg", name: "Skillet Brownies"),
  Foods(index: 195, cal: 100, image: "images/Dessert/Sprinkle-Sugar-Cookies.jpg", name: "Sprinkle Sugar Cookie"),
  Foods(index: 196, cal: 100, image: "images/Dessert/strawberry-dark-chocoloate-truffle-cake.jpg", name: "Strawberry Truffle Cake"),
  Foods(index: 197, cal: 100, image: "images/Dessert/Strawberry-Trifle.jpg", name: "Strawberry Trifle"),
  Foods(index: 198, cal: 100, image: "images/Dessert/Sugar-Cream-Pie.jpg", name: "Sugar Cream Pie"),
  Foods(index: 199, cal: 100, image: "images/Dessert/tart-al-limone.jpg", name: "Tart-al-Limone"),
  Foods(index: 200, cal: 100, image: "images/Dessert/Tres-Leches-Cake.jpg", name: "Tres Leches Cake"),
  Foods(index: 201, cal: 100, image: "images/Dessert/Vanilla-Cupcakes.jpg", name: "Vanilla Cupcake"),
  Foods(index: 202, cal: 100, image: "images/Dessert/Vanilla-Ice-Cream.jpg", name: "Vanilla IceCream"),
  Foods(index: 203, cal: 100, image: "images/Dessert/Vanilla-Meringue-Cookies.jpg", name: "Vanilla Cookie"),
  Foods(index: 204, cal: 100, image: "images/Dessert/White-Chocolate-Raspberry-Cheesecake.jpg", name: "Raspberry Cheesecake"),
];

const appetizerList = const [

  Foods(index: 17, cal: 100, image: "images/appetizer/Fried-Prosciutto-Tortellini.jpg", name: "Tortellini"),
  Foods(index: 21, cal: 100, image: "images/appetizer/Ham-n-Cheese-Biscuit-Stacks.jpg", name: "Ham-n-Cheese"),
  Foods(index: 27, cal: 100, image: "images/appetizer/nan-khatai.jpg", name: "Nan Khatai"),
  Foods(index: 48, cal: 100, image: "images/appetizer/coconut-shrimp-2.jpg", name: "Coconut Shrimp"),
  Foods(index: 49, cal: 100, image: "images/appetizer/cream-cheese-cucumbers-waterbury.jpg", name: "Cheese Cucumbers"),
  Foods(index: 77, cal: 100, image: "images/appetizer/healthy-oatmeal-pancakes-cinnamon-apples.jpg", name: "Oatmeal Pancake"),
  Foods(index: 78, cal: 100, image: "images/appetizer/healthy-oatmeal-with-eapnut-butter-and-banana-recipe.jpg", name: "Oatmeal and Banana"),
  Foods(index: 83, cal: 100, image: "images/appetizer/healthy-turkey-b-l-t-salad.jpg", name: "Turkey Salad"),
  Foods(index: 86, cal: 100, image: "images/appetizer/how-to-make-restaurant-salsa-4.jpg", name: "Salsa"),
  Foods(index: 87, cal: 100, image: "images/appetizer/instant-pot-cheesy-cauliflower-3.jpg", name: "Instant Pot Cauliflower"),
  Foods(index: 93, cal: 100, image: "images/appetizer/keto-berries-and-cream-overnight-oats.jpg", name: "Berries and Cream"),
  Foods(index: 244, cal: 100, image: "images/appetizer/authentic-chinese-egg-rolls-from-a-chinese-person.jpg", name: "Chinese Egg Rolls"),
  Foods(index: 245, cal: 100, image: "images/appetizer/Baked-Brie-with-Caramelized-Onions.jpg", name: "Brie with Caramelized Onions"),
  Foods(index: 246, cal: 100, image: "images/appetizer/banana-nutella-crepe.jpg", name: "Banana Nutella Crepe"),
  Foods(index: 247, cal: 100, image: "images/appetizer/beef-taquitos.jpg", name: "Beef Taquitos"),
  Foods(index: 248, cal: 100, image: "images/appetizer/best-ever-jalapeno-poppers.jpg", name: "Japlapeno Poppers"),
  Foods(index: 249, cal: 100, image: "images/appetizer/Brie-Cheese-Appetizer.jpg", name: "Brie Cheese Appetizer"),
  Foods(index: 250, cal: 100, image: "images/appetizer/Brie-Cups.jpg", name: "Brie Cups"),
  Foods(index: 251, cal: 100, image: "images/appetizer/Cheddar-Cheese-Nippers.jpg", name: "Cheese Nippers"),
  Foods(index: 252, cal: 100, image: "images/appetizer/Chicken-Salad-Wanton-cups.jpg", name: "Chicken Salad Cups"),
  Foods(index: 253, cal: 100, image: "images/appetizer/chocolate_chip_cookies1.jpg", name: "Chocolate chip Cookie"),
  Foods(index: 254, cal: 100, image: "images/appetizer/crab-cakes.jpg", name: "Crab Cake"),
  Foods(index: 255, cal: 100, image: "images/appetizer/crispy-wonton-chips.jpg", name: "Crispy Wonton Chips"),
  Foods(index: 256, cal: 100, image: "images/appetizer/Figs-and-Toasted-Almonds-Brie.jpg", name: "Toasted Almond Brie"),
  Foods(index: 257, cal: 100, image: "images/appetizer/fried-burrata-ball.jpg", name: "Fried Burrata Balls"),
  Foods(index: 258, cal: 100, image: "images/appetizer/Garlicky-Baked-Brie.jpg", name: "Garlicky Brie"),
  Foods(index: 259, cal: 100, image: "images/appetizer/Greek-Meatballs.jpg", name: "Greek Meatballs"),
  Foods(index: 260, cal: 100, image: "images/appetizer/Grilled-Sandwich.jpg", name: "Grilled Sandwich"),
  Foods(index: 261, cal: 100, image: "images/appetizer/jalapeno-poppers.jpg", name: "Jalapeno Poppers"),
  Foods(index: 262, cal: 100, image: "images/appetizer/jamaican-saltfish-fritters.jpg", name: "Jamaican Salt Fish"),
  Foods(index: 263, cal: 100, image: "images/appetizer/Kettle-Corn.jpg", name: "Kettle Corn"),
  Foods(index: 264, cal: 100, image: "images/appetizer/Lavosh.jpg", name: "Lavosh"),
  Foods(index: 265, cal: 100, image: "images/appetizer/Masala-Wings.jpg", name: "Masla Wings"),
  Foods(index: 266, cal: 100, image: "images/appetizer/paleo-plum-muffins.jpg", name: "Plum Muffins"),
  Foods(index: 267, cal: 100, image: "images/appetizer/potato-chips.jpg", name: "Patato Chips"),
  Foods(index: 268, cal: 100, image: "images/appetizer/Pulled-chicken-sandwich.png", name: "Chicken Sandwich"),
  Foods(index: 269, cal: 100, image: "images/appetizer/Pulled-Pork-Masa-Cakes.jpg", name: "Pork Masa Cake"),
  Foods(index: 270, cal: 100, image: "images/appetizer/skewers-with-lemon-chive.jpg", name: "Skewers with Lemon Chive"),
  Foods(index: 271, cal: 100, image: "images/appetizer/smoked-salmon-rolls.jpg", name: "Smoked Salmon Rolls"),
  Foods(index: 272, cal: 100, image: "images/appetizer/Spinach-Puff-Pastry-Rolls.jpg", name: "Pastry Rolls"),
  Foods(index: 273, cal: 100, image: "images/appetizer/Swet-Potato-Nachos.jpg", name: "Potato Nachos"),
  Foods(index: 274, cal: 100, image: "images/appetizer/Tuna-Potato-Croquettes.jpg", name: "Tuna Potato Croquettes"),

];

const breakFastList = const [

  Foods(index: 15, cal: 100, image: "images/BreakFast/Egg-Sandwich.jpg", name: "Egg Sandwich"),
  Foods(index: 16, cal: 100, image: "images/BreakFast/eggs.jpg", name: "Eggs"),
  Foods(index: 29, cal: 100, image: "images/BreakFast/Chai.jpg", name: "Chai"),
  Foods(index: 31, cal: 100, image: "images/BreakFast/parata.jpg", name: "Parata"),
  Foods(index: 59, cal: 100, image: "images/BreakFast/healthy-blueberry-pancakes.jpg", name: "Blueberry Pancakes"),
  Foods(index: 205, cal: 100, image: "images/BreakFast/40-second-omelet.jpg", name: "40 Second Omelet"),
  Foods(index: 206, cal: 100, image: "images/BreakFast/aloo-paratha.jpg", name: "Aloo Paratha"),
  Foods(index: 207, cal: 100, image: "images/BreakFast/amlet.jpg", name: "Omelet"),
  Foods(index: 208, cal: 100, image: "images/BreakFast/banana-pancakes.jpg", name: "Banana Pancakes"),
  Foods(index: 209, cal: 100, image: "images/BreakFast/bbq-sandwiches.jpg", name: "BBQ Sandwich"),
  Foods(index: 210, cal: 100, image: "images/BreakFast/biscuits.jpg", name: "Biscuits"),
  Foods(index: 211, cal: 100, image: "images/BreakFast/breakfast-pizza.jpg", name: "BreakFast Pizza"),
  Foods(index: 212, cal: 100, image: "images/BreakFast/cake-rusk.jpg", name: "Cake Rusk"),
  Foods(index: 213, cal: 100, image: "images/BreakFast/cheese-omelete.jpg", name: "Cheese Omelet"),
  Foods(index: 214, cal: 100, image: "images/BreakFast/chicken-cheese-paratha.jpg", name: "Chicken Paratha"),
  Foods(index: 215, cal: 100, image: "images/BreakFast/croissants.jpg", name: "Croissant"),
  Foods(index: 216, cal: 100, image: "images/BreakFast/dal-puri.jpg", name: "Dall Puri"),
  Foods(index: 217, cal: 100, image: "images/BreakFast/easy-egg-omlete.jpg", name: "Egg Omelet"),
  Foods(index: 218, cal: 100, image: "images/BreakFast/egg-bhurji.jpg", name: "Anda Bhurji"),
  Foods(index: 219, cal: 100, image: "images/BreakFast/egg-fried-bread.jpg", name: "Egg Fried Bread"),
  Foods(index: 220, cal: 100, image: "images/BreakFast/egg-muffins.jpg", name: "Egg Muffins"),
  Foods(index: 221, cal: 100, image: "images/BreakFast/egg-salan.jpg", name: "Egg Salan"),
  Foods(index: 222, cal: 100, image: "images/BreakFast/feather-light-pancakes.jpg", name: "Light Pancake"),
  Foods(index: 223, cal: 100, image: "images/BreakFast/fluffy-omelt.jpg", name: "Fluffy Omelet"),
  Foods(index: 224, cal: 100, image: "images/BreakFast/french-omelllete.jpg", name: "French Omelet"),
  Foods(index: 225, cal: 100, image: "images/BreakFast/french-toast.jpg", name: "French Toast"),
  Foods(index: 226, cal: 100, image: "images/BreakFast/gobhi-paratha.jpg", name: "Gobhi Paratha"),
  Foods(index: 227, cal: 100, image: "images/BreakFast/greek-omelette.jpg", name: "Greek Omelet"),
  Foods(index: 228, cal: 100, image: "images/BreakFast/kashmiri-hareesa.jpg", name: "Kasmiri Hareesa"),
  Foods(index: 229, cal: 100, image: "images/BreakFast/khagina.jpg", name: "Khagina"),
  Foods(index: 230, cal: 100, image: "images/BreakFast/low-carb-vanilla-bourbon-french-toast.jpg", name: "Vanilla Toast"),
  Foods(index: 231, cal: 100, image: "images/BreakFast/mango-jam.jpg", name: "Mango Jam"),
  Foods(index: 232, cal: 100, image: "images/BreakFast/meethay-pakoray.jpg", name: "Meethay Pakoray"),
  Foods(index: 233, cal: 100, image: "images/BreakFast/meethi-roti.jpg", name: "Meethi Roti"),
  Foods(index: 234, cal: 100, image: "images/BreakFast/mexican-omelet.jpg", name: "Mexican Omelet"),
  Foods(index: 235, cal: 100, image: "images/BreakFast/overnight-baked-french-toast.jpg", name: "Overnight Toast"),
  Foods(index: 236, cal: 100, image: "images/BreakFast/pizza-paratha.jpg", name: "Pizza Paratha"),
  Foods(index: 237, cal: 100, image: "images/BreakFast/prawn-omelette.jpg", name: "Prawn Omelet"),
  Foods(index: 238, cal: 100, image: "images/BreakFast/rainbow-omelette.jpg", name: "Rainbow Omelet"),
  Foods(index: 239, cal: 100, image: "images/BreakFast/simple-cheese-omelette.jpg", name: "Cheese Omelet"),
  Foods(index: 240, cal: 100, image: "images/BreakFast/soybean.jpg", name: "Soybean"),
  Foods(index: 241, cal: 100, image: "images/BreakFast/stuffed-eggs.jpg", name: "Stuffed eggs"),
  Foods(index: 242, cal: 100, image: "images/BreakFast/syrian-bread.jpg", name: "Syrian Bread"),
  Foods(index: 243, cal: 100, image: "images/BreakFast/white-bread.jpg", name: "White Bread"),
];

const dessertAndAppetizerList = const [
  Foods(index: 13, cal: 100, image: "images/Dessert/Chocolate-Biscuit-Pudding.jpg", name: "Pudding"),
  Foods(index: 14, cal: 100, image: "images/Dessert/CHOCOLATE-CHIP-COOKIES.jpg", name: "Cookies"),
  Foods(index: 18, cal: 100, image: "images/Dessert/gajar-halwa.jpg", name: "Gajar Halwa"),
  Foods(index: 24, cal: 100, image: "images/Dessert/lab-e-shireen.jpg", name: "Lab-e-Shireen"),
  Foods(index: 25, cal: 100, image: "images/Dessert/mango-kulfi.jpg", name: "Mango Kulfi"),
  Foods(index: 30, cal: 100, image: "images/Dessert/pancakes.jpg", name: "Pancakes"),
  Foods(index: 32, cal: 100, image: "images/Dessert/Rice-Kheer.jpg", name: "Rice Kherr"),
  Foods(index: 36, cal: 100, image: "images/Dessert/sooji-halwa.jpg", name: "Sooji Halwa"),
  Foods(index: 46, cal: 100, image: "images/Dessert/blood-orange-beet-smoothie.jpg", name: "Beet Smoothie"),
  Foods(index: 47, cal: 100, image: "images/Dessert/chocolate-pudding-olive-oil-sea-salt.jpg", name: "Chocolate Pudding"),
  Foods(index: 52, cal: 100, image: "images/Dessert/fudgy-pumpkin-brownie-bites.jpg", name: "Fudge Pumpkin"),
  Foods(index: 76, cal: 100, image: "images/Dessert/healthy-oatmeal–chocolate-chip-cookies.jpg", name: "Oatmeal Chocolate"),
  Foods(index: 100, cal: 100, image: "images/Dessert/low-calorie-apple-pie-crunch-topping.jpg", name: "Apple Pie"),
  Foods(index: 104, cal: 100, image: "images/Dessert/low-calorie-fudgy-brownies.jpg", name: "Fudge Brownies"),
  Foods(index: 112, cal: 100, image: "images/Dessert/molten-chocolate-cake.jpg", name: "Molten Chocolate"),
  Foods(index: 115, cal: 100, image: "images/Dessert/protein-powder-pancakes.jpg", name: "Powder Pancake"),
  Foods(index: 117, cal: 100, image: "images/Dessert/raspberry-smoothie.jpg", name: "Raspberry Smoothie"),
  Foods(index: 130, cal: 100, image: "images/Dessert/almond-kulfi.jpg", name: "Almond Kulfi"),
  Foods(index: 145, cal: 100, image: "images/Dessert/Whole30-Lemon-Cake.jpg", name: "Lemon Cake"),
  Foods(index: 149, cal: 100, image: "images/Dessert/Apple-Pie.jpg", name: "Apple Pie"),
  Foods(index: 150, cal: 100, image: "images/Dessert/baked-ricotta-cake.jpg", name: "Ricotta Cake"),
  Foods(index: 151, cal: 100, image: "images/Dessert/banana-chocolate-chip-muffins.jpg", name: "Chocolate Muffin"),
  Foods(index: 152, cal: 100, image: "images/Dessert/banoffee-cream-pudding.jpg", name: "Banoffee Pudding"),
  Foods(index: 153, cal: 100, image: "images/Dessert/biscoff-cookie-butter-ice-cream.jpg", name: "Cookie butter IceCream"),
  Foods(index: 154, cal: 100, image: "images/Dessert/Black-Forest.jpg", name: "Black Forest"),
  Foods(index: 155, cal: 100, image: "images/Dessert/blueberry-icecream.jpg", name: "Blueberry IceCream"),
  Foods(index: 156, cal: 100, image: "images/Dessert/Breakfast-Muffins.jpg", name: "Breakfast Muffins"),
  Foods(index: 157, cal: 100, image: "images/Dessert/burnt-butter-almond-and-honey-cake.jpg", name: "Almond-n-Honey Cake"),
  Foods(index: 158, cal: 100, image: "images/Dessert/Butterscotch-Pudding-Torte.jpg", name: "Butterscotch Pudding"),
  Foods(index: 159, cal: 100, image: "images/Dessert/chocolate-and-ginger-teacake.jpg", name: "Ginger TeaCake"),
  Foods(index: 160, cal: 100, image: "images/Dessert/chocolate-brownies-.jpg", name: "Chocolate Brownies"),
  Foods(index: 161, cal: 100, image: "images/Dessert/Chocolate-Chunk-Muffins.jpg", name: "Chunk Muffins"),
  Foods(index: 162, cal: 100, image: "images/Dessert/chocolate-ice-cream.jpg", name: "Chocolate IceCream"),
  Foods(index: 163, cal: 100, image: "images/Dessert/chocolate-truffle.jpg", name: "Chocolate Truffle"),
  Foods(index: 164, cal: 100, image: "images/Dessert/coconut-yoghurt-cake.jpg", name: "Coconut Yoghurt Cake"),
  Foods(index: 165, cal: 100, image: "images/Dessert/cointreau-souffle.jpg", name: "Cointreau Souffle"),
  Foods(index: 166, cal: 100, image: "images/Dessert/Cookies-and-Cream-Oreo-Brownies.jpg", name: "Oreo Brownies"),
  Foods(index: 167, cal: 100, image: "images/Dessert/Dark-Chocolate-Cheesecake.jpg", name: "Chocolate CheeseCake"),
  Foods(index: 168, cal: 100, image: "images/Dessert/easy-peasy-lemon-meringue-pie.jpg", name: "Lemon Meringue Pie"),
  Foods(index: 169, cal: 100, image: "images/Dessert/favorite-pecan-pie.jpg", name: "Pecan Pie"),
  Foods(index: 170, cal: 100, image: "images/Dessert/First-Place-Coconut-Macaroon.jpg", name: "Coconut Macaroon"),
  Foods(index: 171, cal: 100, image: "images/Dessert/French-Silk-Pie.jpg", name: "French Silk Pie"),
  Foods(index: 172, cal: 100, image: "images/Dessert/Fresh-Strawberry-Cupcakes.jpg", name: "Strawberry CupCake"),
  Foods(index: 173, cal: 100, image: "images/Dessert/Fudgiest-Brownies.jpg", name: "Fudge brownies"),
  Foods(index: 174, cal: 100, image: "images/Dessert/Fried-Apples.jpg", name: "Fried Apples"),
  Foods(index: 175, cal: 100, image: "images/Dessert/Leftover-Rice-Pudding.jpg", name: "Rice Pudding"),
  Foods(index: 176, cal: 100, image: "images/Dessert/lemon_blueberry_muffins.jpg", name: "Lemon Blueberr Muffins"),
  Foods(index: 177, cal: 100, image: "images/Dessert/Lemon-misu.jpg", name: "Lemon Misu"),
  Foods(index: 178, cal: 100, image: "images/Dessert/Lemon-Pound-Cake.jpg", name: "Lemon Pound Cake"),
  Foods(index: 179, cal: 100, image: "images/Dessert/Linzer-Cookies.jpg", name: "Linzer Cookie"),
  Foods(index: 180, cal: 100, image: "images/Dessert/mint-cheesecake-swirl-brownies.jpg", name: "Cheesecake Brownies"),
  Foods(index: 181, cal: 100, image: "images/Dessert/New-York-Style-Cheesecake.jpg", name: "NewYork Cheesecake"),
  Foods(index: 182, cal: 100, image: "images/Dessert/no-bake-tiramisu-cheesecake.jpeg", name: "Tiramisu Cheesecake"),
  Foods(index: 183, cal: 100, image: "images/Dessert/oreo-cheesecake.jpg", name: "Oreo Cheesecake"),
  Foods(index: 184, cal: 100, image: "images/Dessert/Peanut-Butter-Chocolate-Dessert.jpg", name: "Peanut Butter Chocolate"),
  Foods(index: 185, cal: 100, image: "images/Dessert/peanut-butter-pie.jpg", name: "Peanut Butter Pie"),
  Foods(index: 186, cal: 100, image: "images/Dessert/pecan-baklava-roll.jpg", name: "Pecan Baklava Roll"),
  Foods(index: 187, cal: 100, image: "images/Dessert/pecan-chocolate-bread-and-butter-pudding.jpg", name: "Bread and Butter Pudding"),
  Foods(index: 188, cal: 100, image: "images/Dessert/Pineapple-Upside-Down-Cake.jpg", name: "Pineapple Cake"),
  Foods(index: 189, cal: 100, image: "images/Dessert/pistachio-phirni.jpg", name: "Pistachio"),
  Foods(index: 190, cal: 100, image: "images/Dessert/pumpkin-chocolate-chip-muffins.jpg", name: "Pumpkin Chocolate Muffins"),
  Foods(index: 191, cal: 100, image: "images/Dessert/Pumpkin-Pie.jpg", name: "Pumpkin Pie"),
  Foods(index: 192, cal: 100, image: "images/Dessert/red-velvet-cake.jpg", name: "Red Velvet Cake"),
  Foods(index: 193, cal: 100, image: "images/Dessert/red-velvet-kiss-cookies.jpg", name: "Red Velvet Cookie"),
  Foods(index: 194, cal: 100, image: "images/Dessert/Skillet-Brownies-.jpg", name: "Skillet Brownies"),
  Foods(index: 195, cal: 100, image: "images/Dessert/Sprinkle-Sugar-Cookies.jpg", name: "Sprinkle Sugar Cookie"),
  Foods(index: 196, cal: 100, image: "images/Dessert/strawberry-dark-chocoloate-truffle-cake.jpg", name: "Strawberry Truffle Cake"),
  Foods(index: 197, cal: 100, image: "images/Dessert/Strawberry-Trifle.jpg", name: "Strawberry Trifle"),
  Foods(index: 198, cal: 100, image: "images/Dessert/Sugar-Cream-Pie.jpg", name: "Sugar Cream Pie"),
  Foods(index: 199, cal: 100, image: "images/Dessert/tart-al-limone.jpg", name: "Tart-al-Limone"),
  Foods(index: 200, cal: 100, image: "images/Dessert/Tres-Leches-Cake.jpg", name: "Tres Leches Cake"),
  Foods(index: 201, cal: 100, image: "images/Dessert/Vanilla-Cupcakes.jpg", name: "Vanilla Cupcake"),
  Foods(index: 202, cal: 100, image: "images/Dessert/Vanilla-Ice-Cream.jpg", name: "Vanilla IceCream"),
  Foods(index: 203, cal: 100, image: "images/Dessert/Vanilla-Meringue-Cookies.jpg", name: "Canilla Cookie"),
  Foods(index: 204, cal: 100, image: "images/Dessert/White-Chocolate-Raspberry-Cheesecake.jpg", name: "Raspberry Cheesecake"),
  Foods(index: 17, cal: 100, image: "images/appetizer/Fried-Prosciutto-Tortellini.jpg", name: "Tortellini"),
  Foods(index: 21, cal: 100, image: "images/appetizer/Ham-n-Cheese-Biscuit-Stacks.jpg", name: "Ham-n-Cheese"),
  Foods(index: 27, cal: 100, image: "images/appetizer/nan-khatai.jpg", name: "Nan Khatai"),
  Foods(index: 48, cal: 100, image: "images/appetizer/coconut-shrimp-2.jpg", name: "Coconut Shrimp"),
  Foods(index: 49, cal: 100, image: "images/appetizer/cream-cheese-cucumbers-waterbury.jpg", name: "Cheese Cucumbers"),
  Foods(index: 77, cal: 100, image: "images/appetizer/healthy-oatmeal-pancakes-cinnamon-apples.jpg", name: "Oatmeal Pancake"),
  Foods(index: 78, cal: 100, image: "images/appetizer/healthy-oatmeal-with-eapnut-butter-and-banana-recipe.jpg", name: "Oatmeal and Banana"),
  Foods(index: 83, cal: 100, image: "images/appetizer/healthy-turkey-b-l-t-salad.jpg", name: "Turkey Salad"),
  Foods(index: 86, cal: 100, image: "images/appetizer/how-to-make-restaurant-salsa-4.jpg", name: "Salsa"),
  Foods(index: 87, cal: 100, image: "images/appetizer/instant-pot-cheesy-cauliflower-3.jpg", name: "Instant Pot Cauliflower"),
  Foods(index: 93, cal: 100, image: "images/appetizer/keto-berries-and-cream-overnight-oats.jpg", name: "Berries and Cream"),
  Foods(index: 244, cal: 100, image: "images/appetizer/authentic-chinese-egg-rolls-from-a-chinese-person.jpg", name: "Chinese Egg Rolls"),
  Foods(index: 245, cal: 100, image: "images/appetizer/Baked-Brie-with-Caramelized-Onions.jpg", name: "Brie with Caramelized Onions"),
  Foods(index: 246, cal: 100, image: "images/appetizer/banana-nutella-crepe.jpg", name: "Banana Nutella Crepe"),
  Foods(index: 247, cal: 100, image: "images/appetizer/beef-taquitos.jpg", name: "Beef Taquitos"),
  Foods(index: 248, cal: 100, image: "images/appetizer/best-ever-jalapeno-poppers.jpg", name: "Japlapeno Poppers"),
  Foods(index: 249, cal: 100, image: "images/appetizer/Brie-Cheese-Appetizer.jpg", name: "Brie Cheese Appetizer"),
  Foods(index: 250, cal: 100, image: "images/appetizer/Brie-Cups.jpg", name: "Brie Cups"),
  Foods(index: 251, cal: 100, image: "images/appetizer/Cheddar-Cheese-Nippers.jpg", name: "Cheese Nippers"),
  Foods(index: 252, cal: 100, image: "images/appetizer/Chicken-Salad-Wanton-cups.jpg", name: "Chicken Salad Cups"),
  Foods(index: 253, cal: 100, image: "images/appetizer/chocolate_chip_cookies1.jpg", name: "Chocolate chip Cookie"),
  Foods(index: 254, cal: 100, image: "images/appetizer/crab-cakes.jpg", name: "Crab Cake"),
  Foods(index: 255, cal: 100, image: "images/appetizer/crispy-wonton-chips.jpg", name: "Crispy Wonton Chips"),
  Foods(index: 256, cal: 100, image: "images/appetizer/Figs-and-Toasted-Almonds-Brie.jpg", name: "Toasted Almond Brie"),
  Foods(index: 257, cal: 100, image: "images/appetizer/fried-burrata-ball.jpg", name: "Fried Burrata Balls"),
  Foods(index: 258, cal: 100, image: "images/appetizer/Garlicky-Baked-Brie.jpg", name: "Garlicky Brie"),
  Foods(index: 259, cal: 100, image: "images/appetizer/Greek-Meatballs.jpg", name: "Greek Meatballs"),
  Foods(index: 260, cal: 100, image: "images/appetizer/Grilled-Sandwich.jpg", name: "Grilled Sandwich"),
  Foods(index: 261, cal: 100, image: "images/appetizer/jalapeno-poppers.jpg", name: "Jalapeno Poppers"),
  Foods(index: 262, cal: 100, image: "images/appetizer/jamaican-saltfish-fritters.jpg", name: "Jamaican Salt Fish"),
  Foods(index: 263, cal: 100, image: "images/appetizer/Kettle-Corn.jpg", name: "Kettle Corn"),
  Foods(index: 264, cal: 100, image: "images/appetizer/Lavosh.jpg", name: "Lavosh"),
  Foods(index: 265, cal: 100, image: "images/appetizer/Masala-Wings.jpg", name: "Masla Wings"),
  Foods(index: 266, cal: 100, image: "images/appetizer/paleo-plum-muffins.jpg", name: "Plum Muffins"),
  Foods(index: 267, cal: 100, image: "images/appetizer/potato-chips.jpg", name: "Patato Chips"),
  Foods(index: 268, cal: 100, image: "images/appetizer/Pulled-chicken-sandwich.png", name: "Chicken Sandwich"),
  Foods(index: 269, cal: 100, image: "images/appetizer/Pulled-Pork-Masa-Cakes.jpg", name: "Pork Masa Cake"),
  Foods(index: 270, cal: 100, image: "images/appetizer/skewers-with-lemon-chive.jpg", name: "Skewers with Lemon Chive"),
  Foods(index: 271, cal: 100, image: "images/appetizer/smoked-salmon-rolls.jpg", name: "Smoked Salmon Rolls"),
  Foods(index: 272, cal: 100, image: "images/appetizer/Spinach-Puff-Pastry-Rolls.jpg", name: "Pastry Rolls"),
  Foods(index: 273, cal: 100, image: "images/appetizer/Swet-Potato-Nachos.jpg", name: "Potato Nachos"),
  Foods(index: 274, cal: 100, image: "images/appetizer/Tuna-Potato-Croquettes.jpg", name: "Tuna Potato Croquettes"),
];