import 'package:tuple/tuple.dart';

class ingredients{
  final name;
  final cal;
  final fats;
  final protein;
  final carbs;
  final nutrientList;
  const ingredients({
    required this.name,
    required this.cal,
    required this.fats,
    required this.protein,
    required this.carbs,
    required this.nutrientList,
  });
}

const ingredientList = const [
  ingredients(name: "Aloo Gobi", cal: 140.0, fats: 109.0, protein: 14.0, carbs: 8.0, nutrientList: alooGobi),
  // ingredients(name: "Aloo Palak", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chowmein", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Channa Dal", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chapli Kabab", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken Baryani", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken Chargha", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken Kofta", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken Korama", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Malai Tikka", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken Slider", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken Tikka", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Pudding", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Cookies", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Egg Sandwich", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Eggs", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Tortellini", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Gajar Halwa", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Peach Pizza", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Balochi Tikka", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Ham-n-Cheese", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Artichoke", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Keema Naan", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Lab-e-Shireen", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Mango Kulfi", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Masoor Daal", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Nan Khatai", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Glazed Meatballs", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chai", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Pancakes", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Parata", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Rice Kherr", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Sarsoon Saag", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Seekh Kabab", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Shahi Tukda", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Sooji Halwa", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Teriyaki Meatballs", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Tuscan Bean", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Yakhni Pulao", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Pork Chop", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Avocado Crisps", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Banana Nutella", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Beef Skewers", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Beef Stew", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Beet Smoothie", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chocolate Pudding", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Coconut Shrimp", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Cheese Cucumbers", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Crock Pot Beef", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken Noodle", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Fudge Pumpkin", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken fingers", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Rosemary Potatoes", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Cheese Mushrooms", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken Salad", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Barbecue Pizza", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Black Bean Omelet", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Blueberry Pancakes", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Blueberry Cobbler", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Butternut Squash", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Carprese Sandwich", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Burger with Sundried Tomato", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken Fried Rice", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken Brick", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Shrimp Quesadilla", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Sandwich with Pastrami", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Fiery Buffalo Wings", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Grilled Calamari", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Mahi Salsa Verde", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Grilled Veggie Wrap", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Italian Tuna Melt", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken Vegetable", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Meatballs Polenta", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Oatmeal Chocolate", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Oatmeal Pancake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Oatmeal and Banana", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Tenderloin Pork", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Red Pepper Alfredo", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Smokey Eggs", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Spaghetti Tomato Sauce", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Turkey Salad", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Club Sandwich", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Waffles Ham Egg", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Salsa", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Instant Pot Cauliflower", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Instant Pot Chicken", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Shrimp and Broccoli", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Steak Fajitas", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Italian Burger", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Cheese Sandwich", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Berries and Cream", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Pizza Cups", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Roast Chicken", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Shredded Pork", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Zucchini Noodles", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Lentil Veggie Tots", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Apple Pie", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Fettuccine Turkey", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "CheeseStack Sandwich", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken Role", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Fudge Brownies", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Caesar Salad", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Huevos Rancheros", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Ricotta CheeseCake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Spinach Ham", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Tofu Veggie Scramble", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Molten Chocolate", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Pistachio Ball", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Veggie Burger", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Powder Pancake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Pumpkin Chili", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Raspberry Smoothie", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "SwordFish with Blueberry", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Paleo Casserole", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Pan Pork Chops", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Taco Pasta", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Vegan Sausage", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Asian Chicken Meatballs", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken Pot Skickers", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Grilled Chicken Sandwich", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Linguine Clams", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Meatballs Soup", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Almond Kulfi", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Scallops With Chimichurri", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Seared Tuna Tacos", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Steak with Eggs", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Swedish Meatballs", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Spicy Beef", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Veggie Artichoke Dip", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Veggie Bruschetta", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Butternut Ravioli", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Carpese Tomato Tower", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Green Bean Casserole", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Grilled Mexican Corn", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Melted brie Vegetables", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Goat Cheese Salad", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Machine Casserole", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Lemon Cake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken Wings", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Garlic Wings", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Sausage Sheet Pan", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Apple Pie", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Ricotta Cake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chocolate Muffin", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Banoffee Pudding", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Cookie butter IceCream", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Black Forest", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Blueberry IceCream", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Breakfast Muffins", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Almond-n-Honey Cake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Butterscotch Pudding", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Ginger TeaCake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chocolate Brownies", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chunk Muffins", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chocolate IceCream", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chocolate Truffle", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Coconut Yoghurt Cake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Cointreau Souffle", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Oreo Brownies", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chocolate CheeseCake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Lemon Meringue Pie", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Pecan Pie", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Coconut Macaroon", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "French Silk Pie", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Strawberry CupCake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Fudge brownies", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Fried Apples", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Rice Pudding", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Lemon Blueberr Muffins", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Lemon Misu", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Lemon Pound Cake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Linzer Cookie", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Cheesecake Brownies", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "NewYork Cheesecake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Tiramisu Cheesecake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Oreo Cheesecake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Peanut Butter Chocolate", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Peanut Butter Pie", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Pecan Baklava Roll", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Bread and Butter Pudding", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Pineapple Cake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Pistachio", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Pumpkin Chocolate Muffins", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Pumpkin Pie", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Red Velvet Cake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Red Velvet Cookie", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Skillet Brownies", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Sprinkle Sugar Cookie", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Strawberry Truffle Cake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Strawberry Trifle", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Sugar Cream Pie", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Tart-al-Limone", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Tres Leches Cake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Vanilla Cupcake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Vanilla IceCream", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Vanilla Cookie", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Raspberry Cheesecake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "40 Second Omelet", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Aloo Paratha", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Omelet", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Banana Pancakes", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "BBQ Sandwich", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Biscuits", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "BreakFast Pizza", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Cake Rusk", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Cheese Omelet", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken Paratha", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Croissant", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Dall Puri", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Egg Omelet", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Anda Bhurji", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Egg Fried Bread", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Egg Muffins", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Egg Salan", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Light Pancake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Fluffy Omelet", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "French Omelet", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "French Toast", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Gobhi Paratha", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Greek Omelet", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Kasmiri Hareesa", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Khagina", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Vanilla Toast", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Mango Jam", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Meethay Pakoray", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Meethi Roti", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Mexican Omelet", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Overnight Toast", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Pizza Paratha", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Prawn Omelet", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Rainbow Omelet", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Cheese Omelet", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Soybean", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Stuffed eggs", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Syrian Bread", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "White Bread", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chinese Egg Rolls", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Brie with Caramelized Onions", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Banana Nutella Crepe", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Beef Taquitos", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Japlapeno Poppers", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Brie Cheese Appetizer", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Brie Cups", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Cheese Nippers", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken Salad Cups", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chocolate chip Cookie", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Crab Cake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Crispy Wonton Chips", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Toasted Almond Brie", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Fried Burrata Balls", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Garlicky Brie", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Greek Meatballs", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Grilled Sandwich", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Jalapeno Poppers", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Jamaican Salt Fish", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Kettle Corn", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Lavosh", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Masla Wings", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Plum Muffins", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Patato Chips", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Chicken Sandwich", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Pork Masa Cake", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Skewers with Lemon Chive", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Smoked Salmon Rolls", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Pastry Rolls", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Potato Nachos", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Tuna Potato Croquettes", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Aloo Gobi", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Aloo Gobi", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Aloo Gobi", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Aloo Gobi", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Aloo Gobi", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Aloo Gobi", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Aloo Gobi", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Aloo Gobi", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Aloo Gobi", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Aloo Gobi", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Aloo Gobi", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Aloo Gobi", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
  // ingredients(name: "Aloo Gobi", cal: cal, fats: fats, protein: protein, carbs: carbs, nutrientList: nutrientList),
];

const List<Tuple2> alooGobi = [
  const Tuple2<String, String>("Nutrition", "48.4g"),
  const Tuple2<String, String>("Nutrition", "48.4g"),
  const Tuple2<String, String>("Nutrition", "48.4g"),
  const Tuple2<String, String>("Nutrition", "48.4g"),
  const Tuple2<String, String>("Nutrition", "48.4g"),
  const Tuple2<String, String>("Nutrition", "48.4g"),
  const Tuple2<String, String>("Nutrition", "48.4g"),
  const Tuple2<String, String>("Nutrition", "48.4g"),
  const Tuple2<String, String>("Nutrition", "48.4g"),
  const Tuple2<String, String>("Nutrition", "48.4g"),
  const Tuple2<String, String>("Nutrition", "48.4g"),
];